// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ActivityLog
    {
        public int Id { get; set; }
        public int IdClientPartnerProfile { get; set; }
        public string PremierSalesForce { get; set; }
        public string Activity { get; set; }
        public DateTime Date { get; set; }

        public virtual ClientPartnerProfile IdClientPartnerProfileNavigation { get; set; }
    }
}