// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class AdditionalExpense
    {
        public int Id { get; set; }
        public int? Invoice { get; set; }
        public bool? Requested { get; set; }
        public string Concept { get; set; }
        public decimal? Amount { get; set; }
        public int? Currency { get; set; }

        public virtual CatCurrency CurrencyNavigation { get; set; }
        public virtual Invoice InvoiceNavigation { get; set; }
    }
}