// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class AdministrativeContactsConsultant
    {
        public AdministrativeContactsConsultant()
        {
            DocumentAdministrativeContactsConsultants = new HashSet<DocumentAdministrativeContactsConsultant>();
        }

        public int Id { get; set; }
        public int? AreasCoverage { get; set; }
        public string Photo { get; set; }
        public int? ContactType { get; set; }
        public string ContactName { get; set; }
        public string Title { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int? City { get; set; }
        public string Comments { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual AreasCoverageConsultant AreasCoverageNavigation { get; set; }
        public virtual CatCity CityNavigation { get; set; }
        public virtual CatContactType ContactTypeNavigation { get; set; }
        public virtual ICollection<DocumentAdministrativeContactsConsultant> DocumentAdministrativeContactsConsultants { get; set; }
    }
}