// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class AirportTransportationService
    {
        public AirportTransportationService()
        {
            CommentAirportTransportationServices = new HashSet<CommentAirportTransportationService>();
            DocumentAirportTransportationServices = new HashSet<DocumentAirportTransportationService>();
            ExtensionAirportTransportationServices = new HashSet<ExtensionAirportTransportationService>();
            FamilyMemberTransportServices = new HashSet<FamilyMemberTransportService>();
            PaymentAirportTransportationServices = new HashSet<PaymentAirportTransportationService>();
            ReminderAirportTransportationServices = new HashSet<ReminderAirportTransportationService>();
        }

        public int Id { get; set; }
        public int WorkOrderServicesId { get; set; }
        public DateTime AuthoDate { get; set; }
        public DateTime AuthoAcceptanceDate { get; set; }
        public int? ApplicantId { get; set; }
        public bool? Coordination { get; set; }
        public int StatusId { get; set; }
        public string ProjectFee { get; set; }
        public DateTime ServiceCompletionDate { get; set; }
        public string Comments { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? TransportType { get; set; }
        public DateTime? ServiceDate { get; set; }
        public string TimeServicesHour { get; set; }
        public string TimeServicesMinute { get; set; }
        public string FlightNumber { get; set; }
        public string PickUpLocation { get; set; }
        public string DropOffLocation { get; set; }
        public int? NumberLuggage { get; set; }
        public int? SupplierPartner { get; set; }
        public string DriverName { get; set; }
        public string DriverContact { get; set; }
        public string Vehicle { get; set; }
        public string VehicleColor { get; set; }
        public string PlateNumber { get; set; }
        public bool? Pet { get; set; }

        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual SupplierPartnerProfileService SupplierPartnerNavigation { get; set; }
        public virtual CatTransportType TransportTypeNavigation { get; set; }
        public virtual WorkOrderService WorkOrderServices { get; set; }
        public virtual ICollection<CommentAirportTransportationService> CommentAirportTransportationServices { get; set; }
        public virtual ICollection<DocumentAirportTransportationService> DocumentAirportTransportationServices { get; set; }
        public virtual ICollection<ExtensionAirportTransportationService> ExtensionAirportTransportationServices { get; set; }
        public virtual ICollection<FamilyMemberTransportService> FamilyMemberTransportServices { get; set; }
        public virtual ICollection<PaymentAirportTransportationService> PaymentAirportTransportationServices { get; set; }
        public virtual ICollection<ReminderAirportTransportationService> ReminderAirportTransportationServices { get; set; }
    }
}