// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class AmenitiesHousingList
    {
        public int HousingList { get; set; }
        public int Amenitie { get; set; }

        public virtual CatAmenitie AmenitieNavigation { get; set; }
        public virtual HousingList HousingListNavigation { get; set; }
    }
}