// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Answer
    {
        public Answer()
        {
            ParticipantEvaluations = new HashSet<ParticipantEvaluation>();
        }

        public int Id { get; set; }
        public int Evaluation { get; set; }
        public string Answer1 { get; set; }
        public bool Correct { get; set; }
        public int Order { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual Evaluation EvaluationNavigation { get; set; }
        public virtual ICollection<ParticipantEvaluation> ParticipantEvaluations { get; set; }
    }
}