// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class AreaOrientation
    {
        public AreaOrientation()
        {
            CommentAreaOrientations = new HashSet<CommentAreaOrientation>();
            DocumentAreaOrientations = new HashSet<DocumentAreaOrientation>();
            ExtensionAreaOrientations = new HashSet<ExtensionAreaOrientation>();
            ReminderAreaOrientations = new HashSet<ReminderAreaOrientation>();
            SchoolingAreaOrientations = new HashSet<SchoolingAreaOrientation>();
        }

        public int Id { get; set; }
        public int WorkOrderServicesId { get; set; }
        public DateTime AuthoDate { get; set; }
        public DateTime AuthoAcceptanceDate { get; set; }
        public bool? Coordination { get; set; }
        public int StatusId { get; set; }
        public DateTime? AuthoDateExtension { get; set; }
        public DateTime? AuthoAcceptanceDateExtension { get; set; }
        public string Time { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public bool? Supermarks { get; set; }
        public bool? ShoppingSocialAreas { get; set; }
        public bool? Parks { get; set; }
        public bool? ExtracurricularActivities { get; set; }
        public bool? Housing { get; set; }
        public bool? Schooling { get; set; }
        public string Comment { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual WorkOrderService WorkOrderServices { get; set; }
        public virtual ICollection<CommentAreaOrientation> CommentAreaOrientations { get; set; }
        public virtual ICollection<DocumentAreaOrientation> DocumentAreaOrientations { get; set; }
        public virtual ICollection<ExtensionAreaOrientation> ExtensionAreaOrientations { get; set; }
        public virtual ICollection<ReminderAreaOrientation> ReminderAreaOrientations { get; set; }
        public virtual ICollection<SchoolingAreaOrientation> SchoolingAreaOrientations { get; set; }
    }
}