// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class AreasCoverageService
    {
        public AreasCoverageService()
        {
            AdministrativeContactsServices = new HashSet<AdministrativeContactsService>();
            Campuses = new HashSet<Campus>();
            CityAreasCoverageServices = new HashSet<CityAreasCoverageService>();
            ConsultantContactsServices = new HashSet<ConsultantContactsService>();
            DocumentAreasCoverageServices = new HashSet<DocumentAreasCoverageService>();
            PaymentInformationServices = new HashSet<PaymentInformationService>();
        }

        public int Id { get; set; }
        public int? SupplierPartnerProfileService { get; set; }
        public int? Type { get; set; }
        public int? Country { get; set; }
        public int? PrimaryCity { get; set; }
        public string CurrentAddress { get; set; }
        public string ZipCode { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCountry CountryNavigation { get; set; }
        public virtual CatCity PrimaryCityNavigation { get; set; }
        public virtual SupplierPartnerProfileService SupplierPartnerProfileServiceNavigation { get; set; }
        public virtual CatAreaCoverageType TypeNavigation { get; set; }
        public virtual ICollection<AdministrativeContactsService> AdministrativeContactsServices { get; set; }
        public virtual ICollection<Campus> Campuses { get; set; }
        public virtual ICollection<CityAreasCoverageService> CityAreasCoverageServices { get; set; }
        public virtual ICollection<ConsultantContactsService> ConsultantContactsServices { get; set; }
        public virtual ICollection<DocumentAreasCoverageService> DocumentAreasCoverageServices { get; set; }
        public virtual ICollection<PaymentInformationService> PaymentInformationServices { get; set; }
    }
}