// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class AssignedServiceSuplier
    {
        public int Id { get; set; }
        public int? ImmigrationSupplierPartnerId { get; set; }
        public int? RelocationSupplierPartnerId { get; set; }
        public int? ServiceOrderServicesId { get; set; }

        public virtual ImmigrationSupplierPartner ImmigrationSupplierPartner { get; set; }
        public virtual RelocationSupplierPartner RelocationSupplierPartner { get; set; }
        public virtual WorkOrderService ServiceOrderServices { get; set; }
    }
}