// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class AssignedTeam
    {
        public int AssignedBy { get; set; }
        public int AssignedTo { get; set; }

        public virtual ProfileUser AssignedByNavigation { get; set; }
        public virtual ProfileUser AssignedToNavigation { get; set; }
    }
}