// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class AssigneeInformation
    {
        public AssigneeInformation()
        {
            DependentInformations = new HashSet<DependentInformation>();
            LanguagesSpokens = new HashSet<LanguagesSpoken>();
            PetsNavigation = new HashSet<Pet>();
        }

        public int Id { get; set; }
        public int? UserId { get; set; }
        public string Photo { get; set; }
        public string AssigneeName { get; set; }
        public int? SexId { get; set; }
        public DateTime? Birth { get; set; }
        public int? Age { get; set; }
        public int? NationalityId { get; set; }
        public int? MaritalStatusId { get; set; }
        public string MobilePhone { get; set; }
        public string WorkPhone { get; set; }
        public int? PolicyTypeId { get; set; }
        public int? AssignmentDuration { get; set; }
        public int? AssignmentDurationTime { get; set; }
        public DateTime? InitialArrival { get; set; }
        public DateTime? FinalMove { get; set; }
        public int? HomeCountryId { get; set; }
        public int? HomeCityId { get; set; }
        public string CurrentPosition { get; set; }
        public int? HostCountry { get; set; }
        public int? HostCityId { get; set; }
        public string NewPosition { get; set; }
        public bool? DependentInformation { get; set; }
        public bool? Pets { get; set; }
        public string Email { get; set; }
        public int? ServiceRecordId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatDuration AssignmentDurationTimeNavigation { get; set; }
        public virtual CatCity HomeCity { get; set; }
        public virtual CatCountry HomeCountry { get; set; }
        public virtual CatCity HostCity { get; set; }
        public virtual CatCountry HostCountryNavigation { get; set; }
        public virtual CatMaritalstatus MaritalStatus { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual ServiceRecord ServiceRecord { get; set; }
        public virtual CatSex Sex { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<DependentInformation> DependentInformations { get; set; }
        public virtual ICollection<LanguagesSpoken> LanguagesSpokens { get; set; }
        public virtual ICollection<Pet> PetsNavigation { get; set; }
    }
}