// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class AssigneeFeedback
    {
        public int Id { get; set; }
        public int? ServiceOrderServicesId { get; set; }
        public int? AssigneeId { get; set; }
        public int? Rating { get; set; }
        public string Feedback { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual DependentInformation Assignee { get; set; }
        public virtual WorkOrderService ServiceOrderServices { get; set; }
    }
}