// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class BundledServicesWorkOrder
    {
        public BundledServicesWorkOrder()
        {
            BundledServices = new HashSet<BundledService>();
        }

        public int Id { get; set; }
        public int? WorkOrderId { get; set; }
        public string TotalTime { get; set; }
        public string ProjectedFee { get; set; }
        public bool? Package { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual WorkOrder WorkOrder { get; set; }
        public virtual ICollection<BundledService> BundledServices { get; set; }
    }
}