// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CallAssistant
    {
        public int CallId { get; set; }
        public int Assistant { get; set; }

        public virtual User AssistantNavigation { get; set; }
        public virtual Call Call { get; set; }
    }
}