// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatAssitanceWith
    {
        public CatAssitanceWith()
        {
            DepartureAssistanceWiths = new HashSet<DepartureAssistanceWith>();
        }

        public int Id { get; set; }
        public string Assistance { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<DepartureAssistanceWith> DepartureAssistanceWiths { get; set; }
    }
}