// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatAmenitie
    {
        public CatAmenitie()
        {
            AmenitiesHousingLists = new HashSet<AmenitiesHousingList>();
            RelHousingAmenities = new HashSet<RelHousingAmenitie>();
            RelHousingAreaOrientations = new HashSet<RelHousingAreaOrientation>();
        }

        public int Id { get; set; }
        public string Amenitie { get; set; }

        public virtual ICollection<AmenitiesHousingList> AmenitiesHousingLists { get; set; }
        public virtual ICollection<RelHousingAmenitie> RelHousingAmenities { get; set; }
        public virtual ICollection<RelHousingAreaOrientation> RelHousingAreaOrientations { get; set; }
    }
}