// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatAreaCoverageType
    {
        public CatAreaCoverageType()
        {
            AreasCoverageConsultants = new HashSet<AreasCoverageConsultant>();
            AreasCoverageServices = new HashSet<AreasCoverageService>();
        }

        public int Id { get; set; }
        public string Type { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<AreasCoverageConsultant> AreasCoverageConsultants { get; set; }
        public virtual ICollection<AreasCoverageService> AreasCoverageServices { get; set; }
    }
}