// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatBreed
    {
        public int Id { get; set; }
        public string Breed { get; set; }
        public int PetTypeId { get; set; }
        public bool Status { get; set; }

        public virtual CatPetType PetType { get; set; }
    }
}