// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatBankAccountType
    {
        public CatBankAccountType()
        {
            LandLordBankDetails = new HashSet<LandLordBankDetail>();
            LandLordBanks = new HashSet<LandLordBank>();
            LandlordDetailsHomes = new HashSet<LandlordDetailsHome>();
            PaymentInformationProfiles = new HashSet<PaymentInformationProfile>();
            WireTransferConsultants = new HashSet<WireTransferConsultant>();
            WireTransferPaymentConcepts = new HashSet<WireTransferPaymentConcept>();
            WireTransferServices = new HashSet<WireTransferService>();
        }

        public int Id { get; set; }
        public string AccountType { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<LandLordBankDetail> LandLordBankDetails { get; set; }
        public virtual ICollection<LandLordBank> LandLordBanks { get; set; }
        public virtual ICollection<LandlordDetailsHome> LandlordDetailsHomes { get; set; }
        public virtual ICollection<PaymentInformationProfile> PaymentInformationProfiles { get; set; }
        public virtual ICollection<WireTransferConsultant> WireTransferConsultants { get; set; }
        public virtual ICollection<WireTransferPaymentConcept> WireTransferPaymentConcepts { get; set; }
        public virtual ICollection<WireTransferService> WireTransferServices { get; set; }
    }
}