// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatCreditTerm
    {
        public CatCreditTerm()
        {
            SupplierPartnerProfileConsultants = new HashSet<SupplierPartnerProfileConsultant>();
            SupplierPartnerProfileServices = new HashSet<SupplierPartnerProfileService>();
        }

        public int Id { get; set; }
        public string CreditTerm { get; set; }

        public virtual ICollection<SupplierPartnerProfileConsultant> SupplierPartnerProfileConsultants { get; set; }
        public virtual ICollection<SupplierPartnerProfileService> SupplierPartnerProfileServices { get; set; }
    }
}