// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatContactType
    {
        public CatContactType()
        {
            AdministrativeContactsConsultants = new HashSet<AdministrativeContactsConsultant>();
            AdministrativeContactsServices = new HashSet<AdministrativeContactsService>();
        }

        public int Id { get; set; }
        public string Type { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<AdministrativeContactsConsultant> AdministrativeContactsConsultants { get; set; }
        public virtual ICollection<AdministrativeContactsService> AdministrativeContactsServices { get; set; }
    }
}