// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatCoordinator
    {
        public int Id { get; set; }
        public string Coordinator { get; set; }
        public int? CoordinatorTypeId { get; set; }

        public virtual CatCoordinatorType CoordinatorType { get; set; }
    }
}