// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatClient
    {
        public int Id { get; set; }
        public string Client { get; set; }
    }
}