// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatCity
    {
        public CatCity()
        {
            AdministrativeContactsConsultants = new HashSet<AdministrativeContactsConsultant>();
            AdministrativeContactsServices = new HashSet<AdministrativeContactsService>();
            AreasCoverageConsultants = new HashSet<AreasCoverageConsultant>();
            AreasCoverageServices = new HashSet<AreasCoverageService>();
            AssigneeInformationHomeCities = new HashSet<AssigneeInformation>();
            AssigneeInformationHostCities = new HashSet<AssigneeInformation>();
            CatOffices = new HashSet<CatOffice>();
            CityAbouts = new HashSet<CityAbout>();
            CityAreasCoverageConsultants = new HashSet<CityAreasCoverageConsultant>();
            CityAreasCoverageServices = new HashSet<CityAreasCoverageService>();
            CityAttractions = new HashSet<CityAttraction>();
            CityEmergencies = new HashSet<CityEmergency>();
            CityWhatToDos = new HashSet<CityWhatToDo>();
            CityWhereEats = new HashSet<CityWhereEat>();
            ConsultantContactsServices = new HashSet<ConsultantContactsService>();
            Coordinators = new HashSet<Coordinator>();
            CorporateAssistances = new HashSet<CorporateAssistance>();
            DocumentAdministrativeContactsConsultants = new HashSet<DocumentAdministrativeContactsConsultant>();
            DocumentAdministrativeContactsServices = new HashSet<DocumentAdministrativeContactsService>();
            DocumentAreasCoverageConsultants = new HashSet<DocumentAreasCoverageConsultant>();
            DocumentAreasCoverageServices = new HashSet<DocumentAreasCoverageService>();
            DocumentConsultantContactsServices = new HashSet<DocumentConsultantContactsService>();
            DocumentManagements = new HashSet<DocumentManagement>();
            DocumentVehicleConsultants = new HashSet<DocumentVehicleConsultant>();
            DocumentVehicleServices = new HashSet<DocumentVehicleService>();
            LocalDocumentations = new HashSet<LocalDocumentation>();
            Notifications = new HashSet<Notification>();
            OfficeContacts = new HashSet<OfficeContact>();
            OfficeInformations = new HashSet<OfficeInformation>();
            PersonalInformations = new HashSet<PersonalInformation>();
            ProfileUsers = new HashSet<ProfileUser>();
            Renewals = new HashSet<Renewal>();
            RequestPayments = new HashSet<RequestPayment>();
            SchoolsLists = new HashSet<SchoolsList>();
            UpcomingEvents = new HashSet<UpcomingEvent>();
        }

        public int Id { get; set; }
        public string City { get; set; }
        public int IdCountry { get; set; }
        public int? IdTimeZone { get; set; }
        public DateTime? CreateDate { get; set; }

        public virtual CatCountry IdCountryNavigation { get; set; }
        public virtual CatTimeZone IdTimeZoneNavigation { get; set; }
        public virtual ICollection<AdministrativeContactsConsultant> AdministrativeContactsConsultants { get; set; }
        public virtual ICollection<AdministrativeContactsService> AdministrativeContactsServices { get; set; }
        public virtual ICollection<AreasCoverageConsultant> AreasCoverageConsultants { get; set; }
        public virtual ICollection<AreasCoverageService> AreasCoverageServices { get; set; }
        public virtual ICollection<AssigneeInformation> AssigneeInformationHomeCities { get; set; }
        public virtual ICollection<AssigneeInformation> AssigneeInformationHostCities { get; set; }
        public virtual ICollection<CatOffice> CatOffices { get; set; }
        public virtual ICollection<CityAbout> CityAbouts { get; set; }
        public virtual ICollection<CityAreasCoverageConsultant> CityAreasCoverageConsultants { get; set; }
        public virtual ICollection<CityAreasCoverageService> CityAreasCoverageServices { get; set; }
        public virtual ICollection<CityAttraction> CityAttractions { get; set; }
        public virtual ICollection<CityEmergency> CityEmergencies { get; set; }
        public virtual ICollection<CityWhatToDo> CityWhatToDos { get; set; }
        public virtual ICollection<CityWhereEat> CityWhereEats { get; set; }
        public virtual ICollection<ConsultantContactsService> ConsultantContactsServices { get; set; }
        public virtual ICollection<Coordinator> Coordinators { get; set; }
        public virtual ICollection<CorporateAssistance> CorporateAssistances { get; set; }
        public virtual ICollection<DocumentAdministrativeContactsConsultant> DocumentAdministrativeContactsConsultants { get; set; }
        public virtual ICollection<DocumentAdministrativeContactsService> DocumentAdministrativeContactsServices { get; set; }
        public virtual ICollection<DocumentAreasCoverageConsultant> DocumentAreasCoverageConsultants { get; set; }
        public virtual ICollection<DocumentAreasCoverageService> DocumentAreasCoverageServices { get; set; }
        public virtual ICollection<DocumentConsultantContactsService> DocumentConsultantContactsServices { get; set; }
        public virtual ICollection<DocumentManagement> DocumentManagements { get; set; }
        public virtual ICollection<DocumentVehicleConsultant> DocumentVehicleConsultants { get; set; }
        public virtual ICollection<DocumentVehicleService> DocumentVehicleServices { get; set; }
        public virtual ICollection<LocalDocumentation> LocalDocumentations { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<OfficeContact> OfficeContacts { get; set; }
        public virtual ICollection<OfficeInformation> OfficeInformations { get; set; }
        public virtual ICollection<PersonalInformation> PersonalInformations { get; set; }
        public virtual ICollection<ProfileUser> ProfileUsers { get; set; }
        public virtual ICollection<Renewal> Renewals { get; set; }
        public virtual ICollection<RequestPayment> RequestPayments { get; set; }
        public virtual ICollection<SchoolsList> SchoolsLists { get; set; }
        public virtual ICollection<UpcomingEvent> UpcomingEvents { get; set; }
    }
}