// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatCategory
    {
        public CatCategory()
        {
            BundledServices = new HashSet<BundledService>();
            CatServices = new HashSet<CatService>();
            Emails = new HashSet<Email>();
            StandaloneServiceWorkOrders = new HashSet<StandaloneServiceWorkOrder>();
        }

        public int Id { get; set; }
        public string Category { get; set; }
        public int? SericeLineId { get; set; }

        public virtual CatServiceLine SericeLine { get; set; }
        public virtual ICollection<BundledService> BundledServices { get; set; }
        public virtual ICollection<CatService> CatServices { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<StandaloneServiceWorkOrder> StandaloneServiceWorkOrders { get; set; }
    }
}