// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatCountry
    {
        public CatCountry()
        {
            AreasCoverageConsultants = new HashSet<AreasCoverageConsultant>();
            AreasCoverageServices = new HashSet<AreasCoverageService>();
            AssigneeInformationHomeCountries = new HashSet<AssigneeInformation>();
            AssigneeInformationHostCountryNavigations = new HashSet<AssigneeInformation>();
            BundledServices = new HashSet<BundledService>();
            CatCities = new HashSet<CatCity>();
            CatOffices = new HashSet<CatOffice>();
            CorporateAssistances = new HashSet<CorporateAssistance>();
            CountryDocuments = new HashSet<CountryDocument>();
            CountryLeaders = new HashSet<CountryLeader>();
            CountryServices = new HashSet<CountryService>();
            DocumentAirportTransportationServices = new HashSet<DocumentAirportTransportationService>();
            DocumentAreaOrientations = new HashSet<DocumentAreaOrientation>();
            DocumentDepartures = new HashSet<DocumentDeparture>();
            DocumentDependentInformations = new HashSet<DocumentDependentInformation>();
            DocumentHomeFindings = new HashSet<DocumentHomeFinding>();
            DocumentHomePurchases = new HashSet<DocumentHomePurchase>();
            DocumentHomeSales = new HashSet<DocumentHomeSale>();
            DocumentInvoices = new HashSet<DocumentInvoice>();
            DocumentLeaseRenewals = new HashSet<DocumentLeaseRenewal>();
            DocumentManagements = new HashSet<DocumentManagement>();
            DocumentOthers = new HashSet<DocumentOther>();
            DocumentPaymentConcepts = new HashSet<DocumentPaymentConcept>();
            DocumentPredecisionOrientations = new HashSet<DocumentPredecisionOrientation>();
            DocumentPropertyManagements = new HashSet<DocumentPropertyManagement>();
            DocumentRentalFurnitureCoordinations = new HashSet<DocumentRentalFurnitureCoordination>();
            DocumentRequestPayments = new HashSet<DocumentRequestPayment>();
            DocumentSchoolingSearches = new HashSet<DocumentSchoolingSearch>();
            DocumentSettlingIns = new HashSet<DocumentSettlingIn>();
            DocumentTemporaryHousingCoordinatons = new HashSet<DocumentTemporaryHousingCoordinaton>();
            DocumentTenancyManagements = new HashSet<DocumentTenancyManagement>();
            DocumentTransportations = new HashSet<DocumentTransportation>();
            Emails = new HashSet<Email>();
            EntryVisas = new HashSet<EntryVisa>();
            ImmigrationSupplierPartners = new HashSet<ImmigrationSupplierPartner>();
            LegalReviews = new HashSet<LegalReview>();
            LocalDocumentations = new HashSet<LocalDocumentation>();
            Notifications = new HashSet<Notification>();
            OfficeInformations = new HashSet<OfficeInformation>();
            PersonalInformations = new HashSet<PersonalInformation>();
            ProfileUsers = new HashSet<ProfileUser>();
            RelocationSupplierPartners = new HashSet<RelocationSupplierPartner>();
            RequestPayments = new HashSet<RequestPayment>();
            ResidencyPermits = new HashSet<ResidencyPermit>();
            SchoolingAreaOrientations = new HashSet<SchoolingAreaOrientation>();
            SchoolingInformations = new HashSet<SchoolingInformation>();
            Schoolings = new HashSet<Schooling>();
            SchoolsLists = new HashSet<SchoolsList>();
            ServiceCountries = new HashSet<ServiceCountry>();
            ServiceLocationCountries = new HashSet<ServiceLocationCountry>();
            StandaloneServiceWorkOrders = new HashSet<StandaloneServiceWorkOrder>();
            UpcomingEvents = new HashSet<UpcomingEvent>();
            VisaDeregistrations = new HashSet<VisaDeregistration>();
            WorkPermits = new HashSet<WorkPermit>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? IdCurrency { get; set; }
        public int? IdLenguage { get; set; }
        public string Sortname { get; set; }
        public string Phonecode { get; set; }
        public string Flag { get; set; }
        public string Nationality { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCurrency IdCurrencyNavigation { get; set; }
        public virtual CatLanguage IdLenguageNavigation { get; set; }
        public virtual ICollection<AreasCoverageConsultant> AreasCoverageConsultants { get; set; }
        public virtual ICollection<AreasCoverageService> AreasCoverageServices { get; set; }
        public virtual ICollection<AssigneeInformation> AssigneeInformationHomeCountries { get; set; }
        public virtual ICollection<AssigneeInformation> AssigneeInformationHostCountryNavigations { get; set; }
        public virtual ICollection<BundledService> BundledServices { get; set; }
        public virtual ICollection<CatCity> CatCities { get; set; }
        public virtual ICollection<CatOffice> CatOffices { get; set; }
        public virtual ICollection<CorporateAssistance> CorporateAssistances { get; set; }
        public virtual ICollection<CountryDocument> CountryDocuments { get; set; }
        public virtual ICollection<CountryLeader> CountryLeaders { get; set; }
        public virtual ICollection<CountryService> CountryServices { get; set; }
        public virtual ICollection<DocumentAirportTransportationService> DocumentAirportTransportationServices { get; set; }
        public virtual ICollection<DocumentAreaOrientation> DocumentAreaOrientations { get; set; }
        public virtual ICollection<DocumentDeparture> DocumentDepartures { get; set; }
        public virtual ICollection<DocumentDependentInformation> DocumentDependentInformations { get; set; }
        public virtual ICollection<DocumentHomeFinding> DocumentHomeFindings { get; set; }
        public virtual ICollection<DocumentHomePurchase> DocumentHomePurchases { get; set; }
        public virtual ICollection<DocumentHomeSale> DocumentHomeSales { get; set; }
        public virtual ICollection<DocumentInvoice> DocumentInvoices { get; set; }
        public virtual ICollection<DocumentLeaseRenewal> DocumentLeaseRenewals { get; set; }
        public virtual ICollection<DocumentManagement> DocumentManagements { get; set; }
        public virtual ICollection<DocumentOther> DocumentOthers { get; set; }
        public virtual ICollection<DocumentPaymentConcept> DocumentPaymentConcepts { get; set; }
        public virtual ICollection<DocumentPredecisionOrientation> DocumentPredecisionOrientations { get; set; }
        public virtual ICollection<DocumentPropertyManagement> DocumentPropertyManagements { get; set; }
        public virtual ICollection<DocumentRentalFurnitureCoordination> DocumentRentalFurnitureCoordinations { get; set; }
        public virtual ICollection<DocumentRequestPayment> DocumentRequestPayments { get; set; }
        public virtual ICollection<DocumentSchoolingSearch> DocumentSchoolingSearches { get; set; }
        public virtual ICollection<DocumentSettlingIn> DocumentSettlingIns { get; set; }
        public virtual ICollection<DocumentTemporaryHousingCoordinaton> DocumentTemporaryHousingCoordinatons { get; set; }
        public virtual ICollection<DocumentTenancyManagement> DocumentTenancyManagements { get; set; }
        public virtual ICollection<DocumentTransportation> DocumentTransportations { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<EntryVisa> EntryVisas { get; set; }
        public virtual ICollection<ImmigrationSupplierPartner> ImmigrationSupplierPartners { get; set; }
        public virtual ICollection<LegalReview> LegalReviews { get; set; }
        public virtual ICollection<LocalDocumentation> LocalDocumentations { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<OfficeInformation> OfficeInformations { get; set; }
        public virtual ICollection<PersonalInformation> PersonalInformations { get; set; }
        public virtual ICollection<ProfileUser> ProfileUsers { get; set; }
        public virtual ICollection<RelocationSupplierPartner> RelocationSupplierPartners { get; set; }
        public virtual ICollection<RequestPayment> RequestPayments { get; set; }
        public virtual ICollection<ResidencyPermit> ResidencyPermits { get; set; }
        public virtual ICollection<SchoolingAreaOrientation> SchoolingAreaOrientations { get; set; }
        public virtual ICollection<SchoolingInformation> SchoolingInformations { get; set; }
        public virtual ICollection<Schooling> Schoolings { get; set; }
        public virtual ICollection<SchoolsList> SchoolsLists { get; set; }
        public virtual ICollection<ServiceCountry> ServiceCountries { get; set; }
        public virtual ICollection<ServiceLocationCountry> ServiceLocationCountries { get; set; }
        public virtual ICollection<StandaloneServiceWorkOrder> StandaloneServiceWorkOrders { get; set; }
        public virtual ICollection<UpcomingEvent> UpcomingEvents { get; set; }
        public virtual ICollection<VisaDeregistration> VisaDeregistrations { get; set; }
        public virtual ICollection<WorkPermit> WorkPermits { get; set; }
    }
}