// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatCreditCard
    {
        public CatCreditCard()
        {
            CreditCardLandLordDetails = new HashSet<CreditCardLandLordDetail>();
            CreditCardPaymentInformationConsultants = new HashSet<CreditCardPaymentInformationConsultant>();
            CreditCardPaymentInformationServices = new HashSet<CreditCardPaymentInformationService>();
            LandLordBankDetails = new HashSet<LandLordBankDetail>();
        }

        public int Id { get; set; }
        public string CreditCard { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<CreditCardLandLordDetail> CreditCardLandLordDetails { get; set; }
        public virtual ICollection<CreditCardPaymentInformationConsultant> CreditCardPaymentInformationConsultants { get; set; }
        public virtual ICollection<CreditCardPaymentInformationService> CreditCardPaymentInformationServices { get; set; }
        public virtual ICollection<LandLordBankDetail> LandLordBankDetails { get; set; }
    }
}