// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatCoordinatorType
    {
        public CatCoordinatorType()
        {
            CatCoordinators = new HashSet<CatCoordinator>();
            Coordinators = new HashSet<Coordinator>();
            ImmigrationCoodinators = new HashSet<ImmigrationCoodinator>();
            RelocationCoordinators = new HashSet<RelocationCoordinator>();
        }

        public int Id { get; set; }
        public string CoordinatorType { get; set; }

        public virtual ICollection<CatCoordinator> CatCoordinators { get; set; }
        public virtual ICollection<Coordinator> Coordinators { get; set; }
        public virtual ICollection<ImmigrationCoodinator> ImmigrationCoodinators { get; set; }
        public virtual ICollection<RelocationCoordinator> RelocationCoordinators { get; set; }
    }
}