// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatCurrency
    {
        public CatCurrency()
        {
            AdditionalExpenses = new HashSet<AdditionalExpense>();
            AssigmentInformationCurrencyCurrentGrossSalaryNavigations = new HashSet<AssigmentInformation>();
            AssigmentInformationCurrencyNewGrossSalaryNavigations = new HashSet<AssigmentInformation>();
            CatCountries = new HashSet<CatCountry>();
            CatOffices = new HashSet<CatOffice>();
            CompesationBenefits = new HashSet<CompesationBenefit>();
            Concepts = new HashSet<Concept>();
            ContractDetailCurrencyFinalNavigations = new HashSet<ContractDetail>();
            ContractDetailCurrencyNavigations = new HashSet<ContractDetail>();
            CostSavingHomes = new HashSet<CostSavingHome>();
            DepartureCostSavings = new HashSet<DepartureCostSaving>();
            DepartureDetailCurrencyFinalRentPriceNavigations = new HashSet<DepartureDetail>();
            DepartureDetailCurrencyListRentPriceNavigations = new HashSet<DepartureDetail>();
            DepartureDetailCurrencyPenaltyNavigations = new HashSet<DepartureDetail>();
            DepartureDetailsHomes = new HashSet<DepartureDetailsHome>();
            HomeFindingComissionCurrencyNavigations = new HashSet<HomeFinding>();
            HomeFindingCurrencyPurchaseDesiredPriceNavigations = new HashSet<HomeFinding>();
            HomeFindingCurrencyPurchaseFinalPriceNavigations = new HashSet<HomeFinding>();
            HomePurchaseCurrencyCommissions = new HashSet<HomePurchase>();
            HomePurchaseCurrencyPurchaseDesiredPrices = new HashSet<HomePurchase>();
            HomePurchaseCurrencyPurchaseFinalPrices = new HashSet<HomePurchase>();
            HomeSaleCurrencyCommissions = new HashSet<HomeSale>();
            HomeSaleCurrencyFinalPrices = new HashSet<HomeSale>();
            HomeSaleCurrencyListPrices = new HashSet<HomeSale>();
            HousingLists = new HashSet<HousingList>();
            HousingSpecifications = new HashSet<HousingSpecification>();
            LandlordDetailsHomes = new HashSet<LandlordDetailsHome>();
            PaymentCurrencyAdvanceFeeNavigations = new HashSet<Payment>();
            PaymentCurrencyManagementFeeNavigations = new HashSet<Payment>();
            PaymentCurrencyPaymentAmountNavigations = new HashSet<Payment>();
            PaymentCurrencyWireFeeNavigations = new HashSet<Payment>();
            PaymentInformationProfiles = new HashSet<PaymentInformationProfile>();
            PropertyExpenses = new HashSet<PropertyExpense>();
            RentalFurnitureCoordinationCurrencyExtensionNavigations = new HashSet<RentalFurnitureCoordination>();
            RentalFurnitureCoordinationCurrencyNavigations = new HashSet<RentalFurnitureCoordination>();
            Repairs = new HashSet<Repair>();
            SchoolsLists = new HashSet<SchoolsList>();
            SupplierPartnerProfileConsultants = new HashSet<SupplierPartnerProfileConsultant>();
            SupplierPartnerProfileServices = new HashSet<SupplierPartnerProfileService>();
            TermsDeals = new HashSet<TermsDeal>();
            WireTransferConsultants = new HashSet<WireTransferConsultant>();
            WireTransferPaymentConcepts = new HashSet<WireTransferPaymentConcept>();
            WireTransferServices = new HashSet<WireTransferService>();
        }

        public int Id { get; set; }
        public string Currency { get; set; }
        public string Abbreviation { get; set; }
        public string Symbol { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<AdditionalExpense> AdditionalExpenses { get; set; }
        public virtual ICollection<AssigmentInformation> AssigmentInformationCurrencyCurrentGrossSalaryNavigations { get; set; }
        public virtual ICollection<AssigmentInformation> AssigmentInformationCurrencyNewGrossSalaryNavigations { get; set; }
        public virtual ICollection<CatCountry> CatCountries { get; set; }
        public virtual ICollection<CatOffice> CatOffices { get; set; }
        public virtual ICollection<CompesationBenefit> CompesationBenefits { get; set; }
        public virtual ICollection<Concept> Concepts { get; set; }
        public virtual ICollection<ContractDetail> ContractDetailCurrencyFinalNavigations { get; set; }
        public virtual ICollection<ContractDetail> ContractDetailCurrencyNavigations { get; set; }
        public virtual ICollection<CostSavingHome> CostSavingHomes { get; set; }
        public virtual ICollection<DepartureCostSaving> DepartureCostSavings { get; set; }
        public virtual ICollection<DepartureDetail> DepartureDetailCurrencyFinalRentPriceNavigations { get; set; }
        public virtual ICollection<DepartureDetail> DepartureDetailCurrencyListRentPriceNavigations { get; set; }
        public virtual ICollection<DepartureDetail> DepartureDetailCurrencyPenaltyNavigations { get; set; }
        public virtual ICollection<DepartureDetailsHome> DepartureDetailsHomes { get; set; }
        public virtual ICollection<HomeFinding> HomeFindingComissionCurrencyNavigations { get; set; }
        public virtual ICollection<HomeFinding> HomeFindingCurrencyPurchaseDesiredPriceNavigations { get; set; }
        public virtual ICollection<HomeFinding> HomeFindingCurrencyPurchaseFinalPriceNavigations { get; set; }
        public virtual ICollection<HomePurchase> HomePurchaseCurrencyCommissions { get; set; }
        public virtual ICollection<HomePurchase> HomePurchaseCurrencyPurchaseDesiredPrices { get; set; }
        public virtual ICollection<HomePurchase> HomePurchaseCurrencyPurchaseFinalPrices { get; set; }
        public virtual ICollection<HomeSale> HomeSaleCurrencyCommissions { get; set; }
        public virtual ICollection<HomeSale> HomeSaleCurrencyFinalPrices { get; set; }
        public virtual ICollection<HomeSale> HomeSaleCurrencyListPrices { get; set; }
        public virtual ICollection<HousingList> HousingLists { get; set; }
        public virtual ICollection<HousingSpecification> HousingSpecifications { get; set; }
        public virtual ICollection<LandlordDetailsHome> LandlordDetailsHomes { get; set; }
        public virtual ICollection<Payment> PaymentCurrencyAdvanceFeeNavigations { get; set; }
        public virtual ICollection<Payment> PaymentCurrencyManagementFeeNavigations { get; set; }
        public virtual ICollection<Payment> PaymentCurrencyPaymentAmountNavigations { get; set; }
        public virtual ICollection<Payment> PaymentCurrencyWireFeeNavigations { get; set; }
        public virtual ICollection<PaymentInformationProfile> PaymentInformationProfiles { get; set; }
        public virtual ICollection<PropertyExpense> PropertyExpenses { get; set; }
        public virtual ICollection<RentalFurnitureCoordination> RentalFurnitureCoordinationCurrencyExtensionNavigations { get; set; }
        public virtual ICollection<RentalFurnitureCoordination> RentalFurnitureCoordinationCurrencyNavigations { get; set; }
        public virtual ICollection<Repair> Repairs { get; set; }
        public virtual ICollection<SchoolsList> SchoolsLists { get; set; }
        public virtual ICollection<SupplierPartnerProfileConsultant> SupplierPartnerProfileConsultants { get; set; }
        public virtual ICollection<SupplierPartnerProfileService> SupplierPartnerProfileServices { get; set; }
        public virtual ICollection<TermsDeal> TermsDeals { get; set; }
        public virtual ICollection<WireTransferConsultant> WireTransferConsultants { get; set; }
        public virtual ICollection<WireTransferPaymentConcept> WireTransferPaymentConcepts { get; set; }
        public virtual ICollection<WireTransferService> WireTransferServices { get; set; }
    }
}