// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatDay
    {
        public CatDay()
        {
            CalendarConsultantContactsConsultants = new HashSet<CalendarConsultantContactsConsultant>();
            RepeatThePaymentConcepts = new HashSet<RepeatThePaymentConcept>();
            RepeatTheRecurrenceRequestPayments = new HashSet<RepeatTheRecurrenceRequestPayment>();
        }

        public int Id { get; set; }
        public string Day { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<CalendarConsultantContactsConsultant> CalendarConsultantContactsConsultants { get; set; }
        public virtual ICollection<RepeatThePaymentConcept> RepeatThePaymentConcepts { get; set; }
        public virtual ICollection<RepeatTheRecurrenceRequestPayment> RepeatTheRecurrenceRequestPayments { get; set; }
    }
}