// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatDeliviredIn
    {
        public int Id { get; set; }
        public string ServiceType { get; set; }
    }
}