// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatDuration
    {
        public CatDuration()
        {
            AssigneeInformations = new HashSet<AssigneeInformation>();
            Calls = new HashSet<Call>();
            CompesationBenefits = new HashSet<CompesationBenefit>();
            PropertyExpenses = new HashSet<PropertyExpense>();
            RecurrencePaymentConcepts = new HashSet<RecurrencePaymentConcept>();
            RecurrenceRequestPayments = new HashSet<RecurrenceRequestPayment>();
            RentalFurnitureCoordinations = new HashSet<RentalFurnitureCoordination>();
            Transportations = new HashSet<Transportation>();
        }

        public int Id { get; set; }
        public string Duration { get; set; }
        public string Recurrence { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdateDate { get; set; }

        public virtual ICollection<AssigneeInformation> AssigneeInformations { get; set; }
        public virtual ICollection<Call> Calls { get; set; }
        public virtual ICollection<CompesationBenefit> CompesationBenefits { get; set; }
        public virtual ICollection<PropertyExpense> PropertyExpenses { get; set; }
        public virtual ICollection<RecurrencePaymentConcept> RecurrencePaymentConcepts { get; set; }
        public virtual ICollection<RecurrenceRequestPayment> RecurrenceRequestPayments { get; set; }
        public virtual ICollection<RentalFurnitureCoordination> RentalFurnitureCoordinations { get; set; }
        public virtual ICollection<Transportation> Transportations { get; set; }
    }
}