// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatDocumentStatus
    {
        public CatDocumentStatus()
        {
            DocumentConsultantContactsConsultants = new HashSet<DocumentConsultantContactsConsultant>();
            DocumentLocationCountries = new HashSet<DocumentLocationCountry>();
            DocumentServiceCountries = new HashSet<DocumentServiceCountry>();
        }

        public int Id { get; set; }
        public string Status { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<DocumentConsultantContactsConsultant> DocumentConsultantContactsConsultants { get; set; }
        public virtual ICollection<DocumentLocationCountry> DocumentLocationCountries { get; set; }
        public virtual ICollection<DocumentServiceCountry> DocumentServiceCountries { get; set; }
    }
}