// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatElement
    {
        public CatElement()
        {
            Evaluations = new HashSet<Evaluation>();
            Themes = new HashSet<Theme>();
        }

        public int Id { get; set; }
        public string Element { get; set; }
        public int? Type { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual ICollection<Theme> Themes { get; set; }
    }
}