// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatFilterReport
    {
        public CatFilterReport()
        {
            Filters = new HashSet<Filter>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? Type { get; set; }

        public virtual ICollection<Filter> Filters { get; set; }
    }
}