// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatHighestLevelEducation
    {
        public CatHighestLevelEducation()
        {
            ImmigrationProfiles = new HashSet<ImmigrationProfile>();
        }

        public int Id { get; set; }
        public string HighestLevelEducation { get; set; }

        public virtual ICollection<ImmigrationProfile> ImmigrationProfiles { get; set; }
    }
}