// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatInvoiceType
    {
        public CatInvoiceType()
        {
            Invoices = new HashSet<Invoice>();
        }

        public int Id { get; set; }
        public string Type { get; set; }

        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}