// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatLeaseGuarantee
    {
        public CatLeaseGuarantee()
        {
            HomeFindings = new HashSet<HomeFinding>();
        }

        public int Id { get; set; }
        public string Guarantee { get; set; }

        public virtual ICollection<HomeFinding> HomeFindings { get; set; }
    }
}