// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatLocationType
    {
        public CatLocationType()
        {
            Locations = new HashSet<Location>();
        }

        public int Id { get; set; }
        public string LocationType { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<Location> Locations { get; set; }
    }
}