// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatNotificationSystemType
    {
        public CatNotificationSystemType()
        {
            NotificationSystems = new HashSet<NotificationSystem>();
        }

        public int Id { get; set; }
        public string Type { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedBy { get; set; }

        public virtual ICollection<NotificationSystem> NotificationSystems { get; set; }
    }
}