// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatNotificationType
    {
        public CatNotificationType()
        {
            Notifications = new HashSet<Notification>();
        }

        public int Id { get; set; }
        public string Notification { get; set; }

        public virtual ICollection<Notification> Notifications { get; set; }
    }
}