// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatPaymentTypeStatus
    {
        public CatPaymentTypeStatus()
        {
            PaymentHousings = new HashSet<PaymentHousing>();
        }

        public int Id { get; set; }
        public string Type { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<PaymentHousing> PaymentHousings { get; set; }
    }
}