// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatPetType
    {
        public CatPetType()
        {
            CatBreeds = new HashSet<CatBreed>();
            Pets = new HashSet<Pet>();
        }

        public int Id { get; set; }
        public string PetType { get; set; }
        public bool Status { get; set; }

        public virtual ICollection<CatBreed> CatBreeds { get; set; }
        public virtual ICollection<Pet> Pets { get; set; }
    }
}