// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatProficiency
    {
        public CatProficiency()
        {
            LenguageProficiencies = new HashSet<LenguageProficiency>();
        }

        public int Id { get; set; }
        public string Proficiency { get; set; }

        public virtual ICollection<LenguageProficiency> LenguageProficiencies { get; set; }
    }
}