// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatPropertySection
    {
        public CatPropertySection()
        {
            KeyInventories = new HashSet<KeyInventory>();
            PropertyReportSections = new HashSet<PropertyReportSection>();
        }

        public int Id { get; set; }
        public string PropertySection { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<KeyInventory> KeyInventories { get; set; }
        public virtual ICollection<PropertyReportSection> PropertyReportSections { get; set; }
    }
}