// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatPaymentType
    {
        public CatPaymentType()
        {
            PaymentHousings = new HashSet<PaymentHousing>();
        }

        public int Id { get; set; }
        public string PaymentType { get; set; }

        public virtual ICollection<PaymentHousing> PaymentHousings { get; set; }
    }
}