// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatPropertyType
    {
        public CatPropertyType()
        {
            HousingSpecifications = new HashSet<HousingSpecification>();
        }

        public int Id { get; set; }
        public string PropertyType { get; set; }

        public virtual ICollection<HousingSpecification> HousingSpecifications { get; set; }
    }
}