// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatProperty
    {
        public CatProperty()
        {
            PermanentHomes = new HashSet<PermanentHome>();
        }

        public int Id { get; set; }
        public string Property { get; set; }

        public virtual ICollection<PermanentHome> PermanentHomes { get; set; }
    }
}