// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatPrivacy
    {
        public CatPrivacy()
        {
            CountryDocuments = new HashSet<CountryDocument>();
            DocumentAdministrativeContactsConsultants = new HashSet<DocumentAdministrativeContactsConsultant>();
            DocumentAdministrativeContactsServices = new HashSet<DocumentAdministrativeContactsService>();
            DocumentAirportTransportationServices = new HashSet<DocumentAirportTransportationService>();
            DocumentAreaOrientations = new HashSet<DocumentAreaOrientation>();
            DocumentAreasCoverageConsultants = new HashSet<DocumentAreasCoverageConsultant>();
            DocumentAreasCoverageServices = new HashSet<DocumentAreasCoverageService>();
            DocumentConsultantContactsConsultants = new HashSet<DocumentConsultantContactsConsultant>();
            DocumentConsultantContactsServices = new HashSet<DocumentConsultantContactsService>();
            DocumentDepartures = new HashSet<DocumentDeparture>();
            DocumentHomeFindings = new HashSet<DocumentHomeFinding>();
            DocumentHomePurchases = new HashSet<DocumentHomePurchase>();
            DocumentHomeSales = new HashSet<DocumentHomeSale>();
            DocumentLeaseRenewals = new HashSet<DocumentLeaseRenewal>();
            DocumentLocationCountries = new HashSet<DocumentLocationCountry>();
            DocumentOthers = new HashSet<DocumentOther>();
            DocumentPredecisionOrientations = new HashSet<DocumentPredecisionOrientation>();
            DocumentPropertyManagements = new HashSet<DocumentPropertyManagement>();
            DocumentRentalFurnitureCoordinations = new HashSet<DocumentRentalFurnitureCoordination>();
            DocumentSchoolingSearches = new HashSet<DocumentSchoolingSearch>();
            DocumentServiceCountries = new HashSet<DocumentServiceCountry>();
            DocumentSettlingIns = new HashSet<DocumentSettlingIn>();
            DocumentTemporaryHousingCoordinatons = new HashSet<DocumentTemporaryHousingCoordinaton>();
            DocumentTransportations = new HashSet<DocumentTransportation>();
            DocumentVehicleConsultants = new HashSet<DocumentVehicleConsultant>();
            DocumentVehicleServices = new HashSet<DocumentVehicleService>();
        }

        public int Id { get; set; }
        public string Privacy { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<CountryDocument> CountryDocuments { get; set; }
        public virtual ICollection<DocumentAdministrativeContactsConsultant> DocumentAdministrativeContactsConsultants { get; set; }
        public virtual ICollection<DocumentAdministrativeContactsService> DocumentAdministrativeContactsServices { get; set; }
        public virtual ICollection<DocumentAirportTransportationService> DocumentAirportTransportationServices { get; set; }
        public virtual ICollection<DocumentAreaOrientation> DocumentAreaOrientations { get; set; }
        public virtual ICollection<DocumentAreasCoverageConsultant> DocumentAreasCoverageConsultants { get; set; }
        public virtual ICollection<DocumentAreasCoverageService> DocumentAreasCoverageServices { get; set; }
        public virtual ICollection<DocumentConsultantContactsConsultant> DocumentConsultantContactsConsultants { get; set; }
        public virtual ICollection<DocumentConsultantContactsService> DocumentConsultantContactsServices { get; set; }
        public virtual ICollection<DocumentDeparture> DocumentDepartures { get; set; }
        public virtual ICollection<DocumentHomeFinding> DocumentHomeFindings { get; set; }
        public virtual ICollection<DocumentHomePurchase> DocumentHomePurchases { get; set; }
        public virtual ICollection<DocumentHomeSale> DocumentHomeSales { get; set; }
        public virtual ICollection<DocumentLeaseRenewal> DocumentLeaseRenewals { get; set; }
        public virtual ICollection<DocumentLocationCountry> DocumentLocationCountries { get; set; }
        public virtual ICollection<DocumentOther> DocumentOthers { get; set; }
        public virtual ICollection<DocumentPredecisionOrientation> DocumentPredecisionOrientations { get; set; }
        public virtual ICollection<DocumentPropertyManagement> DocumentPropertyManagements { get; set; }
        public virtual ICollection<DocumentRentalFurnitureCoordination> DocumentRentalFurnitureCoordinations { get; set; }
        public virtual ICollection<DocumentSchoolingSearch> DocumentSchoolingSearches { get; set; }
        public virtual ICollection<DocumentServiceCountry> DocumentServiceCountries { get; set; }
        public virtual ICollection<DocumentSettlingIn> DocumentSettlingIns { get; set; }
        public virtual ICollection<DocumentTemporaryHousingCoordinaton> DocumentTemporaryHousingCoordinatons { get; set; }
        public virtual ICollection<DocumentTransportation> DocumentTransportations { get; set; }
        public virtual ICollection<DocumentVehicleConsultant> DocumentVehicleConsultants { get; set; }
        public virtual ICollection<DocumentVehicleService> DocumentVehicleServices { get; set; }
    }
}