// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatPriceTermsDeal
    {
        public CatPriceTermsDeal()
        {
            TermsDeals = new HashSet<TermsDeal>();
        }

        public int Id { get; set; }
        public string Price { get; set; }

        public virtual ICollection<TermsDeal> TermsDeals { get; set; }
    }
}