// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatReport
    {
        public CatReport()
        {
            Reports = new HashSet<Report>();
        }

        public int Id { get; set; }
        public string Report { get; set; }

        public virtual ICollection<Report> Reports { get; set; }
    }
}