// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatSeverity
    {
        public CatSeverity()
        {
            PropertyManagements = new HashSet<PropertyManagement>();
            ReportAnEvents = new HashSet<ReportAnEvent>();
        }

        public int Id { get; set; }
        public string Severity { get; set; }

        public virtual ICollection<PropertyManagement> PropertyManagements { get; set; }
        public virtual ICollection<ReportAnEvent> ReportAnEvents { get; set; }
    }
}