// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatStatusHousing
    {
        public CatStatusHousing()
        {
            HousingLists = new HashSet<HousingList>();
            HousingStatusHistories = new HashSet<HousingStatusHistory>();
        }

        public int Id { get; set; }
        public string Status { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<HousingList> HousingLists { get; set; }
        public virtual ICollection<HousingStatusHistory> HousingStatusHistories { get; set; }
    }
}