// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatStatus
    {
        public CatStatus()
        {
            ServiceRecords = new HashSet<ServiceRecord>();
        }

        public int Id { get; set; }
        public string Status { get; set; }

        public virtual ICollection<ServiceRecord> ServiceRecords { get; set; }
    }
}