// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatService
    {
        public CatService()
        {
            BundledServices = new HashSet<BundledService>();
            DocumentManagements = new HashSet<DocumentManagement>();
            LocalDocumentations = new HashSet<LocalDocumentation>();
            ServiceLocations = new HashSet<ServiceLocation>();
            Services = new HashSet<Service>();
            StandaloneServiceWorkOrders = new HashSet<StandaloneServiceWorkOrder>();
        }

        public int Id { get; set; }
        public string Service { get; set; }
        public int? CategoryId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCategory Category { get; set; }
        public virtual ICollection<BundledService> BundledServices { get; set; }
        public virtual ICollection<DocumentManagement> DocumentManagements { get; set; }
        public virtual ICollection<LocalDocumentation> LocalDocumentations { get; set; }
        public virtual ICollection<ServiceLocation> ServiceLocations { get; set; }
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<StandaloneServiceWorkOrder> StandaloneServiceWorkOrders { get; set; }
    }
}