// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatSupplierCompany
    {
        public CatSupplierCompany()
        {
            HomeFindingRepairs = new HashSet<HomeFindingRepair>();
        }

        public int Int { get; set; }
        public string SupplierCompany { get; set; }
        public int SupplierTypeId { get; set; }

        public virtual CatSupplierType SupplierType { get; set; }
        public virtual ICollection<HomeFindingRepair> HomeFindingRepairs { get; set; }
    }
}