// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatServiceLine
    {
        public CatServiceLine()
        {
            Calls = new HashSet<Call>();
            CatCategories = new HashSet<CatCategory>();
            ChatConversationImmigrationRelocations = new HashSet<ChatConversationImmigrationRelocation>();
            ClientPartnerProfileExperienceTeams = new HashSet<ClientPartnerProfileExperienceTeam>();
            EmailSends = new HashSet<EmailSend>();
            EmailServiceRecords = new HashSet<EmailServiceRecord>();
            ExperienceSurveys = new HashSet<ExperienceSurvey>();
            ReportDays = new HashSet<ReportDay>();
            ScalateServices = new HashSet<ScalateService>();
            ServiceLocations = new HashSet<ServiceLocation>();
            ServiceScoreAwards = new HashSet<ServiceScoreAward>();
            Services = new HashSet<Service>();
            SupplierPartnerProfileServices = new HashSet<SupplierPartnerProfileService>();
            Tasks = new HashSet<Task>();
            Users = new HashSet<User>();
            WorkOrders = new HashSet<WorkOrder>();
        }

        public int Id { get; set; }
        public string ServiceLine { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool? Status { get; set; }

        public virtual ICollection<Call> Calls { get; set; }
        public virtual ICollection<CatCategory> CatCategories { get; set; }
        public virtual ICollection<ChatConversationImmigrationRelocation> ChatConversationImmigrationRelocations { get; set; }
        public virtual ICollection<ClientPartnerProfileExperienceTeam> ClientPartnerProfileExperienceTeams { get; set; }
        public virtual ICollection<EmailSend> EmailSends { get; set; }
        public virtual ICollection<EmailServiceRecord> EmailServiceRecords { get; set; }
        public virtual ICollection<ExperienceSurvey> ExperienceSurveys { get; set; }
        public virtual ICollection<ReportDay> ReportDays { get; set; }
        public virtual ICollection<ScalateService> ScalateServices { get; set; }
        public virtual ICollection<ServiceLocation> ServiceLocations { get; set; }
        public virtual ICollection<ServiceScoreAward> ServiceScoreAwards { get; set; }
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<SupplierPartnerProfileService> SupplierPartnerProfileServices { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
    }
}