// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatStatusSale
    {
        public CatStatusSale()
        {
            HomeSales = new HashSet<HomeSale>();
        }

        public int Id { get; set; }
        public string Status { get; set; }

        public virtual ICollection<HomeSale> HomeSales { get; set; }
    }
}