// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatSex
    {
        public CatSex()
        {
            AssigneeInformations = new HashSet<AssigneeInformation>();
            DependentInformations = new HashSet<DependentInformation>();
            SchoolingAreaOrientations = new HashSet<SchoolingAreaOrientation>();
            SchoolingInformations = new HashSet<SchoolingInformation>();
        }

        public int Id { get; set; }
        public string Sex { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedBy { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<AssigneeInformation> AssigneeInformations { get; set; }
        public virtual ICollection<DependentInformation> DependentInformations { get; set; }
        public virtual ICollection<SchoolingAreaOrientation> SchoolingAreaOrientations { get; set; }
        public virtual ICollection<SchoolingInformation> SchoolingInformations { get; set; }
    }
}