// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatTypeService
    {
        public CatTypeService()
        {
            BundledServices = new HashSet<BundledService>();
            CorporateAssistances = new HashSet<CorporateAssistance>();
            StandaloneServiceWorkOrders = new HashSet<StandaloneServiceWorkOrder>();
        }

        public int Id { get; set; }
        public string Service { get; set; }

        public virtual ICollection<BundledService> BundledServices { get; set; }
        public virtual ICollection<CorporateAssistance> CorporateAssistances { get; set; }
        public virtual ICollection<StandaloneServiceWorkOrder> StandaloneServiceWorkOrders { get; set; }
    }
}