// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatTimeZone
    {
        public CatTimeZone()
        {
            CatCities = new HashSet<CatCity>();
        }

        public int Id { get; set; }
        public string TimeZone { get; set; }

        public virtual ICollection<CatCity> CatCities { get; set; }
    }
}