// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatTypeHousing
    {
        public CatTypeHousing()
        {
            HousingSpecifications = new HashSet<HousingSpecification>();
        }

        public int Id { get; set; }
        public string TypeHousing { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<HousingSpecification> HousingSpecifications { get; set; }
    }
}