// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatVehicleType
    {
        public CatVehicleType()
        {
            TypeVehiclesSupplierPartnerDetails = new HashSet<TypeVehiclesSupplierPartnerDetail>();
            VehicleConsultants = new HashSet<VehicleConsultant>();
            VehicleServices = new HashSet<VehicleService>();
        }

        public int Id { get; set; }
        public string Type { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<TypeVehiclesSupplierPartnerDetail> TypeVehiclesSupplierPartnerDetails { get; set; }
        public virtual ICollection<VehicleConsultant> VehicleConsultants { get; set; }
        public virtual ICollection<VehicleService> VehicleServices { get; set; }
    }
}