// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CatVisaCategory
    {
        public CatVisaCategory()
        {
            PreviousHostCountries = new HashSet<PreviousHostCountry>();
        }

        public int Id { get; set; }
        public string VisaCategory { get; set; }

        public virtual ICollection<PreviousHostCountry> PreviousHostCountries { get; set; }
    }
}