// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ChatDocumentImmigrationRelocation
    {
        public int Id { get; set; }
        public string FilePath { get; set; }
        public int ChatImmigrationRelocationId { get; set; }
        public DateTime DateComment { get; set; }
        public bool Status { get; set; }

        public virtual ChatImmigrationRelocation ChatImmigrationRelocation { get; set; }
    }
}