// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ChatImmigrationRelocation
    {
        public ChatImmigrationRelocation()
        {
            ChatDocumentImmigrationRelocations = new HashSet<ChatDocumentImmigrationRelocation>();
        }

        public int Id { get; set; }
        public int ChatCoversationId { get; set; }
        public int UserId { get; set; }
        public string Comment { get; set; }
        public DateTime DateComment { get; set; }
        public bool Status { get; set; }

        public virtual ChatConversationImmigrationRelocation ChatCoversation { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ChatDocumentImmigrationRelocation> ChatDocumentImmigrationRelocations { get; set; }
    }
}