// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CityWhereEat
    {
        public CityWhereEat()
        {
            PhotoWhereEats = new HashSet<PhotoWhereEat>();
        }

        public int Id { get; set; }
        public int IdCity { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Description { get; set; }

        public virtual CatCity IdCityNavigation { get; set; }
        public virtual ICollection<PhotoWhereEat> PhotoWhereEats { get; set; }
    }
}