// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CityEmergency
    {
        public CityEmergency()
        {
            PhotoCityEmergencies = new HashSet<PhotoCityEmergency>();
        }

        public int Id { get; set; }
        public int IdCity { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Description { get; set; }

        public virtual CatCity IdCityNavigation { get; set; }
        public virtual ICollection<PhotoCityEmergency> PhotoCityEmergencies { get; set; }
    }
}