// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CityAreasCoverageConsultant
    {
        public int AreasCoverageConsultant { get; set; }
        public int City { get; set; }

        public virtual AreasCoverageConsultant AreasCoverageConsultantNavigation { get; set; }
        public virtual CatCity CityNavigation { get; set; }
    }
}