// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ClientPartnerProfileClient
    {
        public int Id { get; set; }
        public int IdClientFrom { get; set; }
        public int IdClientTo { get; set; }

        public virtual ClientPartnerProfile IdClientFromNavigation { get; set; }
        public virtual ClientPartnerProfile IdClientToNavigation { get; set; }
    }
}