// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ClientPartnerProfile
    {
        public ClientPartnerProfile()
        {
            ActivityLogs = new HashSet<ActivityLog>();
            ClientPartnerProfileClientIdClientFromNavigations = new HashSet<ClientPartnerProfileClient>();
            ClientPartnerProfileClientIdClientToNavigations = new HashSet<ClientPartnerProfileClient>();
            ClientPartnerProfileExperienceTeams = new HashSet<ClientPartnerProfileExperienceTeam>();
            DocumentClientPartnerProfiles = new HashSet<DocumentClientPartnerProfile>();
            GeneralContractPricingInfos = new HashSet<GeneralContractPricingInfo>();
            OfficeInformations = new HashSet<OfficeInformation>();
            ServiceLocations = new HashSet<ServiceLocation>();
            ServiceRecordClients = new HashSet<ServiceRecord>();
            ServiceRecordPartners = new HashSet<ServiceRecord>();
            ServiceScoreAwards = new HashSet<ServiceScoreAward>();
            TermsDeals = new HashSet<TermsDeal>();
        }

        public int Id { get; set; }
        public int? IdTypePartnerClientProfile { get; set; }
        public int? BelongsToPartner { get; set; }
        public string Photo { get; set; }
        public string Name { get; set; }
        public int? IdCompanyType { get; set; }
        public int? Industry { get; set; }
        public DateTime PartnerClientSince { get; set; }
        public DateTime? ApprovalFrom { get; set; }
        public int? IdResponsiblePremierOffice { get; set; }
        public int? AssignedTo { get; set; }
        public int? IdLifeCircle { get; set; }
        public int? IdSuccessProbability { get; set; }
        public int? IdReferralFee { get; set; }
        public int? IdPaymentRecurrence { get; set; }
        public int? IdPricingType { get; set; }
        public string About { get; set; }
        public int? IdStatus { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual User AssignedToNavigation { get; set; }
        public virtual CompanyType IdCompanyTypeNavigation { get; set; }
        public virtual LifeCircle IdLifeCircleNavigation { get; set; }
        public virtual PaymentRecurrence IdPaymentRecurrenceNavigation { get; set; }
        public virtual PricingType IdPricingTypeNavigation { get; set; }
        public virtual ReferralFee IdReferralFeeNavigation { get; set; }
        public virtual ResponsiblePremierOffice IdResponsiblePremierOfficeNavigation { get; set; }
        public virtual StatusClientPartnerProfile IdStatusNavigation { get; set; }
        public virtual SuccessProbability IdSuccessProbabilityNavigation { get; set; }
        public virtual TypePartnerClientProfile IdTypePartnerClientProfileNavigation { get; set; }
        public virtual CatIndustry IndustryNavigation { get; set; }
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
        public virtual ICollection<ClientPartnerProfileClient> ClientPartnerProfileClientIdClientFromNavigations { get; set; }
        public virtual ICollection<ClientPartnerProfileClient> ClientPartnerProfileClientIdClientToNavigations { get; set; }
        public virtual ICollection<ClientPartnerProfileExperienceTeam> ClientPartnerProfileExperienceTeams { get; set; }
        public virtual ICollection<DocumentClientPartnerProfile> DocumentClientPartnerProfiles { get; set; }
        public virtual ICollection<GeneralContractPricingInfo> GeneralContractPricingInfos { get; set; }
        public virtual ICollection<OfficeInformation> OfficeInformations { get; set; }
        public virtual ICollection<ServiceLocation> ServiceLocations { get; set; }
        public virtual ICollection<ServiceRecord> ServiceRecordClients { get; set; }
        public virtual ICollection<ServiceRecord> ServiceRecordPartners { get; set; }
        public virtual ICollection<ServiceScoreAward> ServiceScoreAwards { get; set; }
        public virtual ICollection<TermsDeal> TermsDeals { get; set; }
    }
}