// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ColaboratorMember
    {
        public int Task { get; set; }
        public int Colaborator { get; set; }

        public virtual User ColaboratorNavigation { get; set; }
        public virtual Task TaskNavigation { get; set; }
    }
}