// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CompanyType
    {
        public CompanyType()
        {
            ClientPartnerProfiles = new HashSet<ClientPartnerProfile>();
        }

        public int Id { get; set; }
        public string CompanyType1 { get; set; }

        public virtual ICollection<ClientPartnerProfile> ClientPartnerProfiles { get; set; }
    }
}