// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CompesationBenefit
    {
        public int Id { get; set; }
        public int? Profile { get; set; }
        public int? PlaceWork { get; set; }
        public decimal? BaseCompesation { get; set; }
        public int? Currency { get; set; }
        public decimal? Taxes { get; set; }
        public int? Benefit { get; set; }
        public decimal? Ammount { get; set; }
        public int? Frequency { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatBenefit BenefitNavigation { get; set; }
        public virtual CatCurrency CurrencyNavigation { get; set; }
        public virtual CatDuration FrequencyNavigation { get; set; }
        public virtual PersonalInformation ProfileNavigation { get; set; }
    }
}