// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Concept
    {
        public int Id { get; set; }
        public int? Payment { get; set; }
        public string Concept1 { get; set; }
        public decimal? Amount { get; set; }
        public int? Currency { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedBy { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCurrency CurrencyNavigation { get; set; }
        public virtual Payment PaymentNavigation { get; set; }
    }
}