// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ConclusionServiceReportDay
    {
        public int Id { get; set; }
        public int ServiceReportDayId { get; set; }
        public string Conclusion { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ServiceReportDay ServiceReportDay { get; set; }
    }
}