// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Conversation
    {
        public Conversation()
        {
            Messages = new HashSet<Message>();
            UserGroups = new HashSet<UserGroup>();
        }

        public int Id { get; set; }
        public int? UserTo { get; set; }
        public int? UserReciver { get; set; }
        public bool? Groups { get; set; }
        public string GroupName { get; set; }
        public bool? Status { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }

        public virtual User UserReciverNavigation { get; set; }
        public virtual User UserToNavigation { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<UserGroup> UserGroups { get; set; }
    }
}