// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Coordinator
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public int? SupplierType { get; set; }
        public bool? Immigration { get; set; }
        public bool? Relocation { get; set; }
        public string ContactName { get; set; }
        public string Title { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int? City { get; set; }
        public string Comments { get; set; }
        public int? UserId { get; set; }
        public int? CoordinatorType { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCity CityNavigation { get; set; }
        public virtual CatCoordinatorType CoordinatorTypeNavigation { get; set; }
        public virtual CatSupplierType SupplierTypeNavigation { get; set; }
        public virtual User User { get; set; }
    }
}