// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CostSaving
    {
        public string Id { get; set; }
        public int? HomeFindingId { get; set; }
        public string Comments { get; set; }

        public virtual HomeFinding HomeFinding { get; set; }
    }
}