// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CostSavingDetail
    {
        public int Id { get; set; }
        public int? HomeFindingId { get; set; }
        public string CostType { get; set; }
        public string CostSavings { get; set; }
        public string CostSavingsCurrency { get; set; }
        public string Comments { get; set; }
    }
}