// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CostSavingHome
    {
        public int Id { get; set; }
        public int? HousingList { get; set; }
        public string CostType { get; set; }
        public string CostSavings { get; set; }
        public int? Currency { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCurrency CurrencyNavigation { get; set; }
        public virtual HousingList HousingListNavigation { get; set; }
    }
}