// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CountryPhoneCode
    {
        public int CountriesId { get; set; }
        public string CountriesName { get; set; }
        public string CountriesIsoCode { get; set; }
        public string CountriesIsdCode { get; set; }
    }
}