// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CountryDocument
    {
        public int Id { get; set; }
        public int IdCountry { get; set; }
        public int IdDocumentType { get; set; }
        public string FileRequest { get; set; }
        public string FileName { get; set; }
        public bool? Group { get; set; }
        public int? IdGroup { get; set; }
        public DateTime UploadDate { get; set; }
        public DateTime ExpirationDate { get; set; }
        public string Location { get; set; }
        public int IdStatus { get; set; }
        public int IdPrivacy { get; set; }

        public virtual CatCountry IdCountryNavigation { get; set; }
        public virtual CatDocumentType IdDocumentTypeNavigation { get; set; }
        public virtual CountryDocumentGroup IdGroupNavigation { get; set; }
        public virtual CatPrivacy IdPrivacyNavigation { get; set; }
        public virtual StatusCountryDocument IdStatusNavigation { get; set; }
    }
}