// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CountryLeader
    {
        public int Country { get; set; }
        public int Leader { get; set; }

        public virtual CatCountry CountryNavigation { get; set; }
        public virtual User LeaderNavigation { get; set; }
    }
}