// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Country
    {
        public Country()
        {
            CountryGalleries = new HashSet<CountryGallery>();
        }

        public int Id { get; set; }
        public string Country1 { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public int? UpdatedDate { get; set; }

        public virtual ICollection<CountryGallery> CountryGalleries { get; set; }
    }
}