// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class CreditCardPaymentInformationConsultant
    {
        public int PaymentInformationConsultant { get; set; }
        public int CreditCard { get; set; }

        public virtual CatCreditCard CreditCardNavigation { get; set; }
        public virtual PaymentInformationConsultant PaymentInformationConsultantNavigation { get; set; }
    }
}