// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DeparturePayment
    {
        public int Id { get; set; }
        public int? DepartaureId { get; set; }
        public string PaymentResponsibility { get; set; }
        public string PaymentType { get; set; }
    }
}