// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Departure
    {
        public Departure()
        {
            CommentDepartures = new HashSet<CommentDeparture>();
            DepartureAssistanceWiths = new HashSet<DepartureAssistanceWith>();
            DocumentDepartures = new HashSet<DocumentDeparture>();
            ExtensionDepartures = new HashSet<ExtensionDeparture>();
            ReminderDepartures = new HashSet<ReminderDeparture>();
        }

        public int Id { get; set; }
        public int WorkOrderServicesId { get; set; }
        public DateTime AuthoDate { get; set; }
        public DateTime AuthoAcceptanceDate { get; set; }
        public bool? Coordination { get; set; }
        public int StatusId { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public bool? PropertyDeparture { get; set; }
        public int? PropertyId { get; set; }
        public DateTime? EstimatedDepartureDate { get; set; }
        public DateTime? ActualDepartureDate { get; set; }
        public DateTime? LeaseTermin { get; set; }
        public DateTime? PickupDate { get; set; }
        public string Comments { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual HousingList Property { get; set; }
        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual WorkOrderService WorkOrderServices { get; set; }
        public virtual ICollection<CommentDeparture> CommentDepartures { get; set; }
        public virtual ICollection<DepartureAssistanceWith> DepartureAssistanceWiths { get; set; }
        public virtual ICollection<DocumentDeparture> DocumentDepartures { get; set; }
        public virtual ICollection<ExtensionDeparture> ExtensionDepartures { get; set; }
        public virtual ICollection<ReminderDeparture> ReminderDepartures { get; set; }
    }
}