// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DepartureDetail
    {
        public int Id { get; set; }
        public int? HomeFindingId { get; set; }
        public DateTime? LeaseStartDate { get; set; }
        public DateTime? LeaseEndDate { get; set; }
        public decimal? ListRentPrice { get; set; }
        public int? CurrencyListRentPrice { get; set; }
        public decimal? FinalRentPrice { get; set; }
        public int? CurrencyFinalRentPrice { get; set; }
        public bool? DiplomaticCouse { get; set; }
        public bool? EarlyTerminationNotification { get; set; }
        public int? Penalty { get; set; }
        public decimal? Amount { get; set; }
        public int? CurrencyPenalty { get; set; }
        public bool? PermissionCreditSecurityDeposit { get; set; }
        public int? ReturnSecurityDepositTo { get; set; }

        public virtual CatCurrency CurrencyFinalRentPriceNavigation { get; set; }
        public virtual CatCurrency CurrencyListRentPriceNavigation { get; set; }
        public virtual CatCurrency CurrencyPenaltyNavigation { get; set; }
        public virtual DependentInformation ReturnSecurityDepositToNavigation { get; set; }
    }
}