// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DepartureAssistanceWith
    {
        public int Id { get; set; }
        public int? DepartaureId { get; set; }
        public int? AssistanceWith { get; set; }
        public DateTime? CompletionDate { get; set; }
        public string OtherSpecify { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatAssitanceWith AssistanceWithNavigation { get; set; }
        public virtual Departure Departaure { get; set; }
    }
}