// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DependentImmigrationInfo
    {
        public int Id { get; set; }
        public int? RelationshipId { get; set; }
        public string Name { get; set; }
        public string PassportNumber { get; set; }
        public DateTime? Issue { get; set; }
        public DateTime? Expiration { get; set; }
        public string IssuingAuthority { get; set; }
        public string PlaceIssue { get; set; }
        public DateTime? EntryDateHostCountry { get; set; }
        public string SpecificAttentionPoints { get; set; }
        public int? ImmigrationProfileId { get; set; }
        public int? DependentInformation { get; set; }

        public virtual DependentInformation DependentInformationNavigation { get; set; }
        public virtual ImmigrationProfile ImmigrationProfile { get; set; }
    }
}