// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DependentInformation
    {
        public DependentInformation()
        {
            AssigneeFeedbacks = new HashSet<AssigneeFeedback>();
            BundledServices = new HashSet<BundledService>();
            DepartureDetails = new HashSet<DepartureDetail>();
            DepartureDetailsHomes = new HashSet<DepartureDetailsHome>();
            DependentImmigrationInfos = new HashSet<DependentImmigrationInfo>();
            DocumentAirportTransportationServices = new HashSet<DocumentAirportTransportationService>();
            DocumentAreaOrientations = new HashSet<DocumentAreaOrientation>();
            DocumentCorporateAssistances = new HashSet<DocumentCorporateAssistance>();
            DocumentDependentInformations = new HashSet<DocumentDependentInformation>();
            DocumentDocumentManagements = new HashSet<DocumentDocumentManagement>();
            DocumentEntryVisas = new HashSet<DocumentEntryVisa>();
            DocumentHomeFindings = new HashSet<DocumentHomeFinding>();
            DocumentHomePurchases = new HashSet<DocumentHomePurchase>();
            DocumentHomeSales = new HashSet<DocumentHomeSale>();
            DocumentLeaseRenewals = new HashSet<DocumentLeaseRenewal>();
            DocumentLegalReviews = new HashSet<DocumentLegalReview>();
            DocumentLocalDocumentations = new HashSet<DocumentLocalDocumentation>();
            DocumentNotifications = new HashSet<DocumentNotification>();
            DocumentOthers = new HashSet<DocumentOther>();
            DocumentPredecisionOrientations = new HashSet<DocumentPredecisionOrientation>();
            DocumentPropertyManagements = new HashSet<DocumentPropertyManagement>();
            DocumentRenewals = new HashSet<DocumentRenewal>();
            DocumentRentalFurnitureCoordinations = new HashSet<DocumentRentalFurnitureCoordination>();
            DocumentResidencyPermits = new HashSet<DocumentResidencyPermit>();
            DocumentSchoolingSearches = new HashSet<DocumentSchoolingSearch>();
            DocumentSettlingIns = new HashSet<DocumentSettlingIn>();
            DocumentTemporaryHousingCoordinatons = new HashSet<DocumentTemporaryHousingCoordinaton>();
            DocumentTenancyManagements = new HashSet<DocumentTenancyManagement>();
            DocumentTransportations = new HashSet<DocumentTransportation>();
            DocumentVisaDeregistrations = new HashSet<DocumentVisaDeregistration>();
            DocumentWorkPermits = new HashSet<DocumentWorkPermit>();
            FamilyMemberTransportServices = new HashSet<FamilyMemberTransportService>();
            FamilyMemberTransportations = new HashSet<FamilyMemberTransportation>();
            HomeFindings = new HashSet<HomeFinding>();
            HomePurchases = new HashSet<HomePurchase>();
            HomeSales = new HashSet<HomeSale>();
            LanguageDependentInformations = new HashSet<LanguageDependentInformation>();
            RequestInformationDocuments = new HashSet<RequestInformationDocument>();
            SchoolingAreaOrientations = new HashSet<SchoolingAreaOrientation>();
            SchoolingInformations = new HashSet<SchoolingInformation>();
            SchoolingReports = new HashSet<SchoolingReport>();
            Schoolings = new HashSet<Schooling>();
            SchoolsLists = new HashSet<SchoolsList>();
            StandaloneServiceWorkOrders = new HashSet<StandaloneServiceWorkOrder>();
            TenancyManagements = new HashSet<TenancyManagement>();
        }

        public int Id { get; set; }
        public int RelationshipId { get; set; }
        public string Photo { get; set; }
        public string Name { get; set; }
        public DateTime? Birth { get; set; }
        public int? Age { get; set; }
        public int? NationalityId { get; set; }
        public string AditionalComments { get; set; }
        public int AssigneeInformationId { get; set; }
        public int? LanguagesId { get; set; }
        public string IfOther { get; set; }
        public int? CurrentGrade { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int? Sex { get; set; }

        public virtual AssigneeInformation AssigneeInformation { get; set; }
        public virtual CatRelationship Relationship { get; set; }
        public virtual CatSex SexNavigation { get; set; }
        public virtual ICollection<AssigneeFeedback> AssigneeFeedbacks { get; set; }
        public virtual ICollection<BundledService> BundledServices { get; set; }
        public virtual ICollection<DepartureDetail> DepartureDetails { get; set; }
        public virtual ICollection<DepartureDetailsHome> DepartureDetailsHomes { get; set; }
        public virtual ICollection<DependentImmigrationInfo> DependentImmigrationInfos { get; set; }
        public virtual ICollection<DocumentAirportTransportationService> DocumentAirportTransportationServices { get; set; }
        public virtual ICollection<DocumentAreaOrientation> DocumentAreaOrientations { get; set; }
        public virtual ICollection<DocumentCorporateAssistance> DocumentCorporateAssistances { get; set; }
        public virtual ICollection<DocumentDependentInformation> DocumentDependentInformations { get; set; }
        public virtual ICollection<DocumentDocumentManagement> DocumentDocumentManagements { get; set; }
        public virtual ICollection<DocumentEntryVisa> DocumentEntryVisas { get; set; }
        public virtual ICollection<DocumentHomeFinding> DocumentHomeFindings { get; set; }
        public virtual ICollection<DocumentHomePurchase> DocumentHomePurchases { get; set; }
        public virtual ICollection<DocumentHomeSale> DocumentHomeSales { get; set; }
        public virtual ICollection<DocumentLeaseRenewal> DocumentLeaseRenewals { get; set; }
        public virtual ICollection<DocumentLegalReview> DocumentLegalReviews { get; set; }
        public virtual ICollection<DocumentLocalDocumentation> DocumentLocalDocumentations { get; set; }
        public virtual ICollection<DocumentNotification> DocumentNotifications { get; set; }
        public virtual ICollection<DocumentOther> DocumentOthers { get; set; }
        public virtual ICollection<DocumentPredecisionOrientation> DocumentPredecisionOrientations { get; set; }
        public virtual ICollection<DocumentPropertyManagement> DocumentPropertyManagements { get; set; }
        public virtual ICollection<DocumentRenewal> DocumentRenewals { get; set; }
        public virtual ICollection<DocumentRentalFurnitureCoordination> DocumentRentalFurnitureCoordinations { get; set; }
        public virtual ICollection<DocumentResidencyPermit> DocumentResidencyPermits { get; set; }
        public virtual ICollection<DocumentSchoolingSearch> DocumentSchoolingSearches { get; set; }
        public virtual ICollection<DocumentSettlingIn> DocumentSettlingIns { get; set; }
        public virtual ICollection<DocumentTemporaryHousingCoordinaton> DocumentTemporaryHousingCoordinatons { get; set; }
        public virtual ICollection<DocumentTenancyManagement> DocumentTenancyManagements { get; set; }
        public virtual ICollection<DocumentTransportation> DocumentTransportations { get; set; }
        public virtual ICollection<DocumentVisaDeregistration> DocumentVisaDeregistrations { get; set; }
        public virtual ICollection<DocumentWorkPermit> DocumentWorkPermits { get; set; }
        public virtual ICollection<FamilyMemberTransportService> FamilyMemberTransportServices { get; set; }
        public virtual ICollection<FamilyMemberTransportation> FamilyMemberTransportations { get; set; }
        public virtual ICollection<HomeFinding> HomeFindings { get; set; }
        public virtual ICollection<HomePurchase> HomePurchases { get; set; }
        public virtual ICollection<HomeSale> HomeSales { get; set; }
        public virtual ICollection<LanguageDependentInformation> LanguageDependentInformations { get; set; }
        public virtual ICollection<RequestInformationDocument> RequestInformationDocuments { get; set; }
        public virtual ICollection<SchoolingAreaOrientation> SchoolingAreaOrientations { get; set; }
        public virtual ICollection<SchoolingInformation> SchoolingInformations { get; set; }
        public virtual ICollection<SchoolingReport> SchoolingReports { get; set; }
        public virtual ICollection<Schooling> Schoolings { get; set; }
        public virtual ICollection<SchoolsList> SchoolsLists { get; set; }
        public virtual ICollection<StandaloneServiceWorkOrder> StandaloneServiceWorkOrders { get; set; }
        public virtual ICollection<TenancyManagement> TenancyManagements { get; set; }
    }
}