// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DocumentClientPartnerProfile
    {
        public int Id { get; set; }
        public int IdClientPartnerProfile { get; set; }
        public int IdDocumentType { get; set; }
        public DateTime UploadDate { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
        public bool Privacy { get; set; }
        public string FileName { get; set; }
        public string FileRequest { get; set; }

        public virtual ClientPartnerProfile IdClientPartnerProfileNavigation { get; set; }
        public virtual CatDocumentType IdDocumentTypeNavigation { get; set; }
    }
}