// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DocumentOfficeInformation
    {
        public int Id { get; set; }
        public int IdOfficeInformation { get; set; }
        public int IdDocumentType { get; set; }
        public DateTime UpdatedDate { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string FileRequest { get; set; }

        public virtual CatDocumentType IdDocumentTypeNavigation { get; set; }
        public virtual OfficeInformation IdOfficeInformationNavigation { get; set; }
    }
}