// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DocumentMessage
    {
        public int Id { get; set; }
        public int? Message { get; set; }
        public string FilePath { get; set; }
        public DateTime? Date { get; set; }
        public bool? Status { get; set; }

        public virtual Message MessageNavigation { get; set; }
    }
}