// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DocumentLocationCountry
    {
        public int Id { get; set; }
        public int IdServiceLocationCountry { get; set; }
        public int IdDocumentType { get; set; }
        public DateTime UploadDate { get; set; }
        public int Status { get; set; }
        public int Privacy { get; set; }
        public string FileName { get; set; }
        public string FileRequest { get; set; }

        public virtual CatDocumentType IdDocumentTypeNavigation { get; set; }
        public virtual ServiceLocationCountry IdServiceLocationCountryNavigation { get; set; }
        public virtual CatPrivacy PrivacyNavigation { get; set; }
        public virtual CatDocumentStatus StatusNavigation { get; set; }
    }
}