// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DocumentServiceCountry
    {
        public int Id { get; set; }
        public int? ServiceCountry { get; set; }
        public string FilePath { get; set; }
        public int? DocumentType { get; set; }
        public int? Status { get; set; }
        public int? Privacy { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatDocumentType DocumentTypeNavigation { get; set; }
        public virtual CatPrivacy PrivacyNavigation { get; set; }
        public virtual ServiceCountry ServiceCountryNavigation { get; set; }
        public virtual CatDocumentStatus StatusNavigation { get; set; }
    }
}