// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DocumentAppointment
    {
        public int Id { get; set; }
        public string FileRequest { get; set; }
        public string FileName { get; set; }
        public int AppointmentId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }

        public virtual Appointment Appointment { get; set; }
    }
}