// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DocumentGeneralContractPricingInfo
    {
        public int Id { get; set; }
        public int IdGeneralContractPricingInfo { get; set; }
        public int IdDocumentType { get; set; }
        public DateTime UpdateDate { get; set; }
        public string DocumentName { get; set; }
        public string Description { get; set; }
        public string FileRequest { get; set; }

        public virtual CatDocumentType IdDocumentTypeNavigation { get; set; }
        public virtual GeneralContractPricingInfo IdGeneralContractPricingInfoNavigation { get; set; }
    }
}