// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DocumentManagement
    {
        public DocumentManagement()
        {
            CommentDocumentManagements = new HashSet<CommentDocumentManagement>();
            DocumentDocumentManagements = new HashSet<DocumentDocumentManagement>();
            ReminderDocumentManagements = new HashSet<ReminderDocumentManagement>();
        }

        public int Id { get; set; }
        public DateTime AuthoDate { get; set; }
        public DateTime AuthoAcceptanceDate { get; set; }
        public int ApplicantId { get; set; }
        public int StatusId { get; set; }
        public string Name { get; set; }
        public int? WorkOrderServicesId { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public int? HostCountryId { get; set; }
        public int? HostCityId { get; set; }
        public int? ServiceId { get; set; }
        public int? DocumentTypeId { get; set; }
        public int? SupplierId { get; set; }
        public string ProjectFee { get; set; }
        public DateTime? DocumentCollectionStartDate { get; set; }
        public DateTime? DocumentDeliveryDate { get; set; }
        public DateTime? DocumentExpirationDate { get; set; }
        public DateTime? DocumentCollectionCompletionDate { get; set; }
        public DateTime? AppointmentDate { get; set; }
        public DateTime? ApplicationSubmissionDate { get; set; }
        public DateTime? ApplicationApprovalDate { get; set; }
        public string Comment { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatDocumentType DocumentType { get; set; }
        public virtual CatCity HostCity { get; set; }
        public virtual CatCountry HostCountry { get; set; }
        public virtual CatService Service { get; set; }
        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual ConsultantContactsService Supplier { get; set; }
        public virtual WorkOrderService WorkOrderServices { get; set; }
        public virtual ICollection<CommentDocumentManagement> CommentDocumentManagements { get; set; }
        public virtual ICollection<DocumentDocumentManagement> DocumentDocumentManagements { get; set; }
        public virtual ICollection<ReminderDocumentManagement> ReminderDocumentManagements { get; set; }
    }
}