// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class DocumentLegalReview
    {
        public int Id { get; set; }
        public int LegalReviewId { get; set; }
        public string FileName { get; set; }
        public string FileRequest { get; set; }
        public int? DocumentType { get; set; }
        public int? Relationship { get; set; }
        public DateTime? IssueDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public string IssuingAuthority { get; set; }
        public int? CountryOrigin { get; set; }
        public string Comment { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedBy { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual Nationality CountryOriginNavigation { get; set; }
        public virtual CatDocumentType DocumentTypeNavigation { get; set; }
        public virtual LegalReview LegalReview { get; set; }
        public virtual DependentInformation RelationshipNavigation { get; set; }
    }
}