// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class EducationalBackground
    {
        public int Id { get; set; }
        public int? ImmigrationProfileId { get; set; }
        public string Institution { get; set; }
        public string FieldStudy { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string Degree { get; set; }
        public string ListProfessionalLicenses { get; set; }

        public virtual ImmigrationProfile ImmigrationProfile { get; set; }
    }
}