// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Email
    {
        public Email()
        {
            EmailServiceRecords = new HashSet<EmailServiceRecord>();
        }

        public int Id { get; set; }
        public string NickName { get; set; }
        public string Subject { get; set; }
        public int? CountryId { get; set; }
        public int? ServiceId { get; set; }
        public string Description { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCountry Country { get; set; }
        public virtual CatCategory Service { get; set; }
        public virtual ICollection<EmailServiceRecord> EmailServiceRecords { get; set; }
    }
}