// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class EmailServiceRecord
    {
        public int Id { get; set; }
        public int? ServiceRecordId { get; set; }
        public int? ServiceLine { get; set; }
        public int? EmailId { get; set; }
        public DateTime? Date { get; set; }
        public bool? Completed { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual Email Email { get; set; }
        public virtual CatServiceLine ServiceLineNavigation { get; set; }
        public virtual ServiceRecord ServiceRecord { get; set; }
    }
}