// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class EmergencyContact
    {
        public int Id { get; set; }
        public int? Profile { get; set; }
        public string ContactName { get; set; }
        public int? Relationship { get; set; }
        public string PhoneNumber { get; set; }
        public string HomeNumber { get; set; }
        public string Location { get; set; }

        public virtual PersonalInformation ProfileNavigation { get; set; }
        public virtual CatRelationship RelationshipNavigation { get; set; }
    }
}