// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class EntryVisa
    {
        public EntryVisa()
        {
            CommentsEntryVisas = new HashSet<CommentsEntryVisa>();
            DocumentEntryVisas = new HashSet<DocumentEntryVisa>();
            ExtensionEntryVisas = new HashSet<ExtensionEntryVisa>();
            ReminderEntryVisas = new HashSet<ReminderEntryVisa>();
        }

        public int Id { get; set; }
        public int WorkOrderServicesId { get; set; }
        public DateTime AuthoDate { get; set; }
        public DateTime AuthoAcceptanceDate { get; set; }
        public int StatusId { get; set; }
        public int? ApplicantId { get; set; }
        public string Name { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public int? CountryId { get; set; }
        public int? CityId { get; set; }
        public string City { get; set; }
        public string VisaTypeId { get; set; }
        public int? ConsularServiceId { get; set; }
        public DateTime? DocumentCollectionStartDate { get; set; }
        public DateTime? DocumentDeliveryDate { get; set; }
        public DateTime? DocumentExpirationDate { get; set; }
        public DateTime? DocumentCollectionDompletionDate { get; set; }
        public DateTime? ApplicationSubmissionDate { get; set; }
        public DateTime? ApplicationApprovalDate { get; set; }
        public string Comment { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatConsularService ConsularService { get; set; }
        public virtual CatCountry Country { get; set; }
        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual WorkOrderService WorkOrderServices { get; set; }
        public virtual ICollection<CommentsEntryVisa> CommentsEntryVisas { get; set; }
        public virtual ICollection<DocumentEntryVisa> DocumentEntryVisas { get; set; }
        public virtual ICollection<ExtensionEntryVisa> ExtensionEntryVisas { get; set; }
        public virtual ICollection<ReminderEntryVisa> ReminderEntryVisas { get; set; }
    }
}