// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ExperienceSurveySupplier
    {
        public int Id { get; set; }
        public int? ExperienceSurveyId { get; set; }
        public int? SupplierService { get; set; }
        public int? SupplierConsultant { get; set; }
        public int? General { get; set; }
        public int? ServiceQuality { get; set; }
        public int? Punctuality { get; set; }
        public int? Attention { get; set; }
        public int? Professionalism { get; set; }
        public int? Price { get; set; }
        public int? ResponseTime { get; set; }
        public string Feedback { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ExperienceSurvey ExperienceSurvey { get; set; }
        public virtual ProfileUser SupplierConsultantNavigation { get; set; }
    }
}