// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ExperienceSurvey
    {
        public ExperienceSurvey()
        {
            ExperienceSurveySuppliers = new HashSet<ExperienceSurveySupplier>();
        }

        public int Id { get; set; }
        public int? ServiceRecord { get; set; }
        public int? WorkOrderServicesId { get; set; }
        public int? ServiceLine { get; set; }
        public bool? CompleteServiceRecord { get; set; }
        public DateTime? CompletedDate { get; set; }
        public string Name { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatServiceLine ServiceLineNavigation { get; set; }
        public virtual ServiceRecord ServiceRecordNavigation { get; set; }
        public virtual WorkOrderService WorkOrderServices { get; set; }
        public virtual ICollection<ExperienceSurveySupplier> ExperienceSurveySuppliers { get; set; }
    }
}