// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class FamilyMemberTransportService
    {
        public int TransportService { get; set; }
        public int FamilyMember { get; set; }

        public virtual DependentInformation FamilyMemberNavigation { get; set; }
        public virtual AirportTransportationService TransportServiceNavigation { get; set; }
    }
}