// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class File
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public int Theme { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual Theme ThemeNavigation { get; set; }
    }
}