// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Filter
    {
        public int Id { get; set; }
        public int? Report { get; set; }
        public int? Filter1 { get; set; }
        public int? Value { get; set; }
        public DateTime? FirstDate { get; set; }
        public DateTime? SecondDate { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatFilterReport Filter1Navigation { get; set; }
        public virtual Report ReportNavigation { get; set; }
    }
}