// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Follow
    {
        public int Id { get; set; }
        public int ServiceRecordId { get; set; }
        public int UserId { get; set; }

        public virtual ServiceRecord ServiceRecord { get; set; }
        public virtual User User { get; set; }
    }
}