// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class HomeSale
    {
        public HomeSale()
        {
            CommentHomeSales = new HashSet<CommentHomeSale>();
            DocumentHomeSales = new HashSet<DocumentHomeSale>();
            ReminderHomeSales = new HashSet<ReminderHomeSale>();
            VisitHomeSales = new HashSet<VisitHomeSale>();
        }

        public int Id { get; set; }
        public int? WorkOrderServices { get; set; }
        public bool? Coordination { get; set; }
        public DateTime? AuthoDate { get; set; }
        public DateTime? AuthoAcceptanceDate { get; set; }
        public int? DeliverTo { get; set; }
        public int? StatusId { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public decimal? ListPrice { get; set; }
        public int? CurrencyListPriceId { get; set; }
        public decimal? PurchaseFinalPrice { get; set; }
        public int? CurrencyFinalPriceId { get; set; }
        public bool? Property { get; set; }
        public int? PropertyId { get; set; }
        public int? SaleStatusId { get; set; }
        public string Comment { get; set; }
        public string Agency { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhoneNo { get; set; }
        public int? PropertyCommission { get; set; }
        public decimal? CommissionAmount { get; set; }
        public int? CurrencyCommissionId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCurrency CurrencyCommission { get; set; }
        public virtual CatCurrency CurrencyFinalPrice { get; set; }
        public virtual CatCurrency CurrencyListPrice { get; set; }
        public virtual DependentInformation DeliverToNavigation { get; set; }
        public virtual HousingList PropertyNavigation { get; set; }
        public virtual CatStatusSale SaleStatus { get; set; }
        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual WorkOrderService WorkOrderServicesNavigation { get; set; }
        public virtual ICollection<CommentHomeSale> CommentHomeSales { get; set; }
        public virtual ICollection<DocumentHomeSale> DocumentHomeSales { get; set; }
        public virtual ICollection<ReminderHomeSale> ReminderHomeSales { get; set; }
        public virtual ICollection<VisitHomeSale> VisitHomeSales { get; set; }
    }
}