// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class HousingList
    {
        public HousingList()
        {
            AmenitiesHousingLists = new HashSet<AmenitiesHousingList>();
            CommentHousings = new HashSet<CommentHousing>();
            CostSavingHomes = new HashSet<CostSavingHome>();
            Departures = new HashSet<Departure>();
            DocumentHousings = new HashSet<DocumentHousing>();
            HomeSales = new HashSet<HomeSale>();
            HousingReports = new HashSet<HousingReport>();
            HousingStatusHistories = new HashSet<HousingStatusHistory>();
            Inspections = new HashSet<Inspection>();
            PaymentHousings = new HashSet<PaymentHousing>();
            PropertyReports = new HashSet<PropertyReport>();
            Repairs = new HashSet<Repair>();
            TenancyManagements = new HashSet<TenancyManagement>();
        }

        public int Id { get; set; }
        public int? WorkOrder { get; set; }
        public int? Service { get; set; }
        public int? ServiceType { get; set; }
        public int? PropertyNo { get; set; }
        public bool? Sample { get; set; }
        public int? SupplierPartner { get; set; }
        public int? Supplier { get; set; }
        public DateTime? VisitDate { get; set; }
        public int? HousingStatus { get; set; }
        public int? PropertyType { get; set; }
        public string Address { get; set; }
        public int? Zip { get; set; }
        public string WebSite { get; set; }
        public int? Bedrooms { get; set; }
        public int? Bathrooms { get; set; }
        public int? ParkingSpaces { get; set; }
        public decimal? Price { get; set; }
        public int? Currency { get; set; }
        public string AdditionalComments { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCurrency CurrencyNavigation { get; set; }
        public virtual CatStatusHousing HousingStatusNavigation { get; set; }
        public virtual CatPropertyTypeHousing PropertyTypeNavigation { get; set; }
        public virtual ConsultantContactsService SupplierNavigation { get; set; }
        public virtual SupplierPartnerProfileService SupplierPartnerNavigation { get; set; }
        public virtual WorkOrder WorkOrderNavigation { get; set; }
        public virtual ContractDetail ContractDetail { get; set; }
        public virtual DepartureDetailsHome DepartureDetailsHome { get; set; }
        public virtual LandlordDetailsHome LandlordDetailsHome { get; set; }
        public virtual RenewalDetailHome RenewalDetailHome { get; set; }
        public virtual ICollection<AmenitiesHousingList> AmenitiesHousingLists { get; set; }
        public virtual ICollection<CommentHousing> CommentHousings { get; set; }
        public virtual ICollection<CostSavingHome> CostSavingHomes { get; set; }
        public virtual ICollection<Departure> Departures { get; set; }
        public virtual ICollection<DocumentHousing> DocumentHousings { get; set; }
        public virtual ICollection<HomeSale> HomeSales { get; set; }
        public virtual ICollection<HousingReport> HousingReports { get; set; }
        public virtual ICollection<HousingStatusHistory> HousingStatusHistories { get; set; }
        public virtual ICollection<Inspection> Inspections { get; set; }
        public virtual ICollection<PaymentHousing> PaymentHousings { get; set; }
        public virtual ICollection<PropertyReport> PropertyReports { get; set; }
        public virtual ICollection<Repair> Repairs { get; set; }
        public virtual ICollection<TenancyManagement> TenancyManagements { get; set; }
    }
}