// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class HousingStatusHistory
    {
        public int Id { get; set; }
        public int? Status { get; set; }
        public int? HousingId { get; set; }
        public string Comment { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual HousingList Housing { get; set; }
        public virtual CatStatusHousing StatusNavigation { get; set; }
    }
}