// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class HousingSpecification
    {
        public HousingSpecification()
        {
            RelHousingAmenities = new HashSet<RelHousingAmenitie>();
        }

        public int Id { get; set; }
        public int? WorkOrderServices { get; set; }
        public int? TypeService { get; set; }
        public string AreaInterest { get; set; }
        public int? PropertyTypeId { get; set; }
        public int? Bedroom { get; set; }
        public int? Bathroom { get; set; }
        public string Size { get; set; }
        public int? MetricId { get; set; }
        public string DesiredCommuteTime { get; set; }
        public decimal? Budget { get; set; }
        public int? CurrencyId { get; set; }
        public int? ContractTypeId { get; set; }
        public DateTime? IntendedStartDate { get; set; }
        public int? ParkingSpace { get; set; }
        public string AdditionalComments { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatContractType ContractType { get; set; }
        public virtual CatCurrency Currency { get; set; }
        public virtual CatMetric Metric { get; set; }
        public virtual CatPropertyType PropertyType { get; set; }
        public virtual CatTypeHousing TypeServiceNavigation { get; set; }
        public virtual WorkOrderService WorkOrderServicesNavigation { get; set; }
        public virtual ICollection<RelHousingAmenitie> RelHousingAmenities { get; set; }
    }
}