// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class KeyInventory
    {
        public int Id { get; set; }
        public int? PropertyReport { get; set; }
        public int? Quantity { get; set; }
        public int? Section { get; set; }
        public string Description { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual PropertyReport PropertyReportNavigation { get; set; }
        public virtual CatPropertySection SectionNavigation { get; set; }
    }
}