// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class LandLordBankDetail
    {
        public int Id { get; set; }
        public int? LandlordBankId { get; set; }
        public int? PaymentMethod { get; set; }
        public int? CreditCard { get; set; }
        public bool? FiscalInvoice { get; set; }
        public int? AccountType { get; set; }
        public string AccountHoldersName { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string RoutingNumber { get; set; }
        public string SwiftBicCode { get; set; }
        public int? Currency { get; set; }
        public decimal? WireFeeApprox { get; set; }
        public string BankAddress { get; set; }
        public bool? InternationalPaymentAcceptance { get; set; }
        public string PayToOrderOf { get; set; }
        public string Comment { get; set; }

        public virtual CatBankAccountType AccountTypeNavigation { get; set; }
        public virtual CatCreditCard CreditCardNavigation { get; set; }
        public virtual LandLordBank LandlordBank { get; set; }
        public virtual CatPaymetMethod PaymentMethodNavigation { get; set; }
    }
}