// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class LandLordBank
    {
        public LandLordBank()
        {
            LandLordBankDetails = new HashSet<LandLordBankDetail>();
        }

        public int Id { get; set; }
        public int? HomeFindingId { get; set; }
        public int? AccountType { get; set; }
        public string GeneralComments { get; set; }
        public string Comments { get; set; }

        public virtual CatBankAccountType AccountTypeNavigation { get; set; }
        public virtual ICollection<LandLordBankDetail> LandLordBankDetails { get; set; }
    }
}