// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class LanguagesSpoken
    {
        public int AssignneInformation { get; set; }
        public int Languages { get; set; }

        public virtual AssigneeInformation AssignneInformationNavigation { get; set; }
    }
}