// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class LanguangeSpokenSchoolingInformation
    {
        public int SchoolingInformation { get; set; }
        public int LanguageSpoken { get; set; }

        public virtual CatLanguage LanguageSpokenNavigation { get; set; }
        public virtual SchoolingInformation SchoolingInformationNavigation { get; set; }
    }
}