// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class LanguageDependentInformation
    {
        public int Dependent { get; set; }
        public int Language { get; set; }

        public virtual DependentInformation DependentNavigation { get; set; }
        public virtual CatLanguage LanguageNavigation { get; set; }
    }
}