// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class LeaseRenewal
    {
        public LeaseRenewal()
        {
            CommentLeaseRenewals = new HashSet<CommentLeaseRenewal>();
            DocumentLeaseRenewals = new HashSet<DocumentLeaseRenewal>();
            ReminderLeaseRenewals = new HashSet<ReminderLeaseRenewal>();
        }

        public int Id { get; set; }
        public int? WorkOrderServices { get; set; }
        public DateTime? AuthoDate { get; set; }
        public DateTime? AuthoAcceptanceDate { get; set; }
        public int? DeliverTo { get; set; }
        public int? StatusId { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public int? Property { get; set; }
        public int? CreationBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual WorkOrderService WorkOrderServicesNavigation { get; set; }
        public virtual ICollection<CommentLeaseRenewal> CommentLeaseRenewals { get; set; }
        public virtual ICollection<DocumentLeaseRenewal> DocumentLeaseRenewals { get; set; }
        public virtual ICollection<ReminderLeaseRenewal> ReminderLeaseRenewals { get; set; }
    }
}