// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class LegalReview
    {
        public LegalReview()
        {
            CommentLegalReviews = new HashSet<CommentLegalReview>();
            DocumentLegalReviews = new HashSet<DocumentLegalReview>();
            ReminderLegalReviews = new HashSet<ReminderLegalReview>();
        }

        public int Id { get; set; }
        public DateTime AuthoDate { get; set; }
        public DateTime AuthoAcceptanceDate { get; set; }
        public int ApplicantId { get; set; }
        public int StatusId { get; set; }
        public string Name { get; set; }
        public int? WorkOrderServicesId { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public int? HostCountryId { get; set; }
        public int? BilliableHours { get; set; }
        public string Comment { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCountry HostCountry { get; set; }
        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual WorkOrderService WorkOrderServices { get; set; }
        public virtual ICollection<CommentLegalReview> CommentLegalReviews { get; set; }
        public virtual ICollection<DocumentLegalReview> DocumentLegalReviews { get; set; }
        public virtual ICollection<ReminderLegalReview> ReminderLegalReviews { get; set; }
    }
}