// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class LenguageProficiency
    {
        public int Id { get; set; }
        public int? LanguageId { get; set; }
        public int? ProficiencyId { get; set; }
        public string Comments { get; set; }
        public int? ImmigrationProfileId { get; set; }

        public virtual ImmigrationProfile ImmigrationProfile { get; set; }
        public virtual CatLanguage Language { get; set; }
        public virtual CatProficiency Proficiency { get; set; }
    }
}