// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class LifeCircle
    {
        public LifeCircle()
        {
            ClientPartnerProfiles = new HashSet<ClientPartnerProfile>();
        }

        public int Id { get; set; }
        public string LifeCircle1 { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<ClientPartnerProfile> ClientPartnerProfiles { get; set; }
    }
}