// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Location
    {
        public int Id { get; set; }
        public int? MapItId { get; set; }
        public int? LocationType { get; set; }
        public int? Service { get; set; }
        public string LocationName { get; set; }
        public string Address { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }

        public virtual CatLocationType LocationTypeNavigation { get; set; }
        public virtual MapIt MapIt { get; set; }
    }
}