// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class MapIt
    {
        public MapIt()
        {
            Locations = new HashSet<Location>();
        }

        public int Id { get; set; }
        public int? ServiceRecord { get; set; }
        public int? SupplierPartner { get; set; }
        public int? ServiceLine { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? CompletedDate { get; set; }
        public string DriverName { get; set; }
        public string DriverContact { get; set; }
        public string Vehicle { get; set; }
        public string PlateNumber { get; set; }
        public string Comments { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ServiceRecord ServiceRecordNavigation { get; set; }
        public virtual ProfileUser SupplierPartnerNavigation { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}