// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Message
    {
        public Message()
        {
            DocumentMessages = new HashSet<DocumentMessage>();
        }

        public int Id { get; set; }
        public int? Conversation { get; set; }
        public int UserId { get; set; }
        public string Message1 { get; set; }
        public DateTime Time { get; set; }
        public bool Status { get; set; }

        public virtual Conversation ConversationNavigation { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<DocumentMessage> DocumentMessages { get; set; }
    }
}