// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Nationality
    {
        public Nationality()
        {
            AssigneeInformations = new HashSet<AssigneeInformation>();
            DocumentCorporateAssistances = new HashSet<DocumentCorporateAssistance>();
            DocumentDocumentManagements = new HashSet<DocumentDocumentManagement>();
            DocumentEntryVisas = new HashSet<DocumentEntryVisa>();
            DocumentLegalReviews = new HashSet<DocumentLegalReview>();
            DocumentLocalDocumentations = new HashSet<DocumentLocalDocumentation>();
            DocumentNotifications = new HashSet<DocumentNotification>();
            DocumentOthers = new HashSet<DocumentOther>();
            DocumentRenewals = new HashSet<DocumentRenewal>();
            DocumentResidencyPermits = new HashSet<DocumentResidencyPermit>();
            DocumentVisaDeregistrations = new HashSet<DocumentVisaDeregistration>();
            DocumentWorkPermits = new HashSet<DocumentWorkPermit>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Nationality1 { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<AssigneeInformation> AssigneeInformations { get; set; }
        public virtual ICollection<DocumentCorporateAssistance> DocumentCorporateAssistances { get; set; }
        public virtual ICollection<DocumentDocumentManagement> DocumentDocumentManagements { get; set; }
        public virtual ICollection<DocumentEntryVisa> DocumentEntryVisas { get; set; }
        public virtual ICollection<DocumentLegalReview> DocumentLegalReviews { get; set; }
        public virtual ICollection<DocumentLocalDocumentation> DocumentLocalDocumentations { get; set; }
        public virtual ICollection<DocumentNotification> DocumentNotifications { get; set; }
        public virtual ICollection<DocumentOther> DocumentOthers { get; set; }
        public virtual ICollection<DocumentRenewal> DocumentRenewals { get; set; }
        public virtual ICollection<DocumentResidencyPermit> DocumentResidencyPermits { get; set; }
        public virtual ICollection<DocumentVisaDeregistration> DocumentVisaDeregistrations { get; set; }
        public virtual ICollection<DocumentWorkPermit> DocumentWorkPermits { get; set; }
    }
}