// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Notification
    {
        public Notification()
        {
            CommentNotifications = new HashSet<CommentNotification>();
            DocumentNotifications = new HashSet<DocumentNotification>();
            ReminderNotifications = new HashSet<ReminderNotification>();
        }

        public int Id { get; set; }
        public DateTime AuthoDate { get; set; }
        public DateTime AuthoAcceptanceDate { get; set; }
        public int ApplicantId { get; set; }
        public int StatusId { get; set; }
        public string Name { get; set; }
        public int? WorkOrderServicesId { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public int? HostCountryId { get; set; }
        public int? HostCityId { get; set; }
        public int? NotificationTypeId { get; set; }
        public DateTime? ApplicationSubmissionDate { get; set; }
        public DateTime? ApplicationApprovalDate { get; set; }
        public DateTime? AppointmentDate { get; set; }
        public string Comment { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCity HostCity { get; set; }
        public virtual CatCountry HostCountry { get; set; }
        public virtual CatNotificationType NotificationType { get; set; }
        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual WorkOrderService WorkOrderServices { get; set; }
        public virtual ICollection<CommentNotification> CommentNotifications { get; set; }
        public virtual ICollection<DocumentNotification> DocumentNotifications { get; set; }
        public virtual ICollection<ReminderNotification> ReminderNotifications { get; set; }
    }
}