// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class NotificationSystem
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int? NotificationType { get; set; }
        public int? ServiceRecord { get; set; }
        public TimeSpan? Time { get; set; }
        public int? UserFrom { get; set; }
        public bool? Accept { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string Color { get; set; }
        public int? UserTo { get; set; }
        public bool? Archive { get; set; }
        public bool? View { get; set; }

        public virtual CatNotificationSystemType NotificationTypeNavigation { get; set; }
        public virtual ServiceRecord ServiceRecordNavigation { get; set; }
        public virtual User UserFromNavigation { get; set; }
        public virtual User UserToNavigation { get; set; }
    }
}