// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class OfficeContact
    {
        public OfficeContact()
        {
            Invoices = new HashSet<Invoice>();
            ServiceRecordAuthorizedByImmigrationNavigations = new HashSet<ServiceRecord>();
            ServiceRecordAuthorizedByRelocationNavigations = new HashSet<ServiceRecord>();
        }

        public int Id { get; set; }
        public int IdOfficeInformation { get; set; }
        public int IdContactType { get; set; }
        public string ContactName { get; set; }
        public string Tittle { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int IdCity { get; set; }

        public virtual CatCity IdCityNavigation { get; set; }
        public virtual OfficeContactType IdContactTypeNavigation { get; set; }
        public virtual OfficeInformation IdOfficeInformationNavigation { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<ServiceRecord> ServiceRecordAuthorizedByImmigrationNavigations { get; set; }
        public virtual ICollection<ServiceRecord> ServiceRecordAuthorizedByRelocationNavigations { get; set; }
    }
}