// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class OfficeInformation
    {
        public OfficeInformation()
        {
            DocumentOfficeInformations = new HashSet<DocumentOfficeInformation>();
            Invoices = new HashSet<Invoice>();
            OfficeContacts = new HashSet<OfficeContact>();
            PaymentInformationOffices = new HashSet<PaymentInformationOffice>();
        }

        public int Id { get; set; }
        public int IdClientPartnerProfile { get; set; }
        public int IdTypeOffice { get; set; }
        public string CommercialName { get; set; }
        public string LegalName { get; set; }
        public int IdCountry { get; set; }
        public int IdCity { get; set; }
        public string CurrentAddress { get; set; }
        public int ZipCode { get; set; }

        public virtual CatCity IdCityNavigation { get; set; }
        public virtual ClientPartnerProfile IdClientPartnerProfileNavigation { get; set; }
        public virtual CatCountry IdCountryNavigation { get; set; }
        public virtual TypeOffice IdTypeOfficeNavigation { get; set; }
        public virtual ICollection<DocumentOfficeInformation> DocumentOfficeInformations { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<OfficeContact> OfficeContacts { get; set; }
        public virtual ICollection<PaymentInformationOffice> PaymentInformationOffices { get; set; }
    }
}