// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class OfficeContactType
    {
        public OfficeContactType()
        {
            OfficeContacts = new HashSet<OfficeContact>();
        }

        public int Id { get; set; }
        public string ContactType { get; set; }

        public virtual ICollection<OfficeContact> OfficeContacts { get; set; }
    }
}