// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Office
    {
        public int Consultant { get; set; }
        public int Office1 { get; set; }

        public virtual ProfileUser ConsultantNavigation { get; set; }
        public virtual CatOffice Office1Navigation { get; set; }
    }
}