// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class OperationLeader
    {
        public int CreatedBy { get; set; }
        public int Consultant { get; set; }

        public virtual ProfileUser ConsultantNavigation { get; set; }
        public virtual ProfileUser CreatedByNavigation { get; set; }
    }
}