// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Other
    {
        public Other()
        {
            CommentOthers = new HashSet<CommentOther>();
            DocumentOthers = new HashSet<DocumentOther>();
            ReminderOthers = new HashSet<ReminderOther>();
        }

        public int Id { get; set; }
        public int? WorkOrderServices { get; set; }
        public bool? Coordination { get; set; }
        public DateTime? AuthoDate { get; set; }
        public DateTime? AuthoAcceptanceDate { get; set; }
        public int? DeliverTo { get; set; }
        public int? StatusId { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public string Description { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual WorkOrderService WorkOrderServicesNavigation { get; set; }
        public virtual ICollection<CommentOther> CommentOthers { get; set; }
        public virtual ICollection<DocumentOther> DocumentOthers { get; set; }
        public virtual ICollection<ReminderOther> ReminderOthers { get; set; }
    }
}