// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Participant
    {
        public Participant()
        {
            ParticipantContents = new HashSet<ParticipantContent>();
        }

        public int Id { get; set; }
        public int Training { get; set; }
        public int UserParticipant { get; set; }
        public int? Status { get; set; }
        public DateTime? CompletedDate { get; set; }
        public decimal? Percentage { get; set; }
        public int? Score { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatParticipantStatus StatusNavigation { get; set; }
        public virtual training TrainingNavigation { get; set; }
        public virtual User UserParticipantNavigation { get; set; }
        public virtual ICollection<ParticipantContent> ParticipantContents { get; set; }
    }
}