// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ParticipantContent
    {
        public ParticipantContent()
        {
            ParticipantEvaluations = new HashSet<ParticipantEvaluation>();
        }

        public int Id { get; set; }
        public int Participant { get; set; }
        public int Content { get; set; }
        public bool Complete { get; set; }
        public int? Score { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual Content ContentNavigation { get; set; }
        public virtual Participant ParticipantNavigation { get; set; }
        public virtual ICollection<ParticipantEvaluation> ParticipantEvaluations { get; set; }
    }
}