// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class PassportInformation
    {
        public PassportInformation()
        {
            ImmigrationProfiles = new HashSet<ImmigrationProfile>();
        }

        public int Id { get; set; }
        public string Number { get; set; }
        public DateTime? Issue { get; set; }
        public DateTime? Expiration { get; set; }
        public string IssuingAuthority { get; set; }
        public string PlaceIssue { get; set; }
        public string CurrentAddress { get; set; }
        public string SpecificAttentionPoints { get; set; }

        public virtual ICollection<ImmigrationProfile> ImmigrationProfiles { get; set; }
    }
}