// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class PaymentHousing
    {
        public int Id { get; set; }
        public int? HousingList { get; set; }
        public int? PaymentType { get; set; }
        public int? Responsible { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual HousingList HousingListNavigation { get; set; }
        public virtual CatPaymentTypeStatus PaymentType1 { get; set; }
        public virtual CatPaymentType PaymentTypeNavigation { get; set; }
        public virtual CatResponsablePayment ResponsibleNavigation { get; set; }
    }
}