// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class PaymentInformationService
    {
        public PaymentInformationService()
        {
            CreditCardPaymentInformationServices = new HashSet<CreditCardPaymentInformationService>();
            WireTransferServices = new HashSet<WireTransferService>();
        }

        public int Id { get; set; }
        public int? AreasCoverageService { get; set; }
        public bool? FiscalInvoice { get; set; }
        public bool? CreditCard { get; set; }
        public bool? Checks { get; set; }
        public string PayToOrderOf { get; set; }
        public bool? Cash { get; set; }
        public string Comment { get; set; }
        public string GeneralComment { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual AreasCoverageService AreasCoverageServiceNavigation { get; set; }
        public virtual ICollection<CreditCardPaymentInformationService> CreditCardPaymentInformationServices { get; set; }
        public virtual ICollection<WireTransferService> WireTransferServices { get; set; }
    }
}