// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class PaymentInformationConsultant
    {
        public PaymentInformationConsultant()
        {
            CreditCardPaymentInformationConsultants = new HashSet<CreditCardPaymentInformationConsultant>();
            WireTransferConsultants = new HashSet<WireTransferConsultant>();
        }

        public int Id { get; set; }
        public int? AreasCoverageConsultant { get; set; }
        public bool? FiscalInvoice { get; set; }
        public bool? CreditCard { get; set; }
        public bool? Checks { get; set; }
        public string PayToOrderOf { get; set; }
        public bool? Cash { get; set; }
        public string Comment { get; set; }
        public string GeneralComment { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual AreasCoverageConsultant AreasCoverageConsultantNavigation { get; set; }
        public virtual ICollection<CreditCardPaymentInformationConsultant> CreditCardPaymentInformationConsultants { get; set; }
        public virtual ICollection<WireTransferConsultant> WireTransferConsultants { get; set; }
    }
}