// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Payment
    {
        public Payment()
        {
            CommentPaymentConcepts = new HashSet<CommentPaymentConcept>();
            Concepts = new HashSet<Concept>();
            DocumentPaymentConcepts = new HashSet<DocumentPaymentConcept>();
            RecurrencePaymentConcepts = new HashSet<RecurrencePaymentConcept>();
            WireTransferPaymentConcepts = new HashSet<WireTransferPaymentConcept>();
            WireTransferServicePaymentConcepts = new HashSet<WireTransferServicePaymentConcept>();
        }

        public int Id { get; set; }
        public int? RequestPayment { get; set; }
        public string Desciption { get; set; }
        public bool? Urgent { get; set; }
        public int? ServiceRecord { get; set; }
        public int? WorkOrder { get; set; }
        public int? Service { get; set; }
        public int? WorkOrderServices { get; set; }
        public bool? IfSupplierPartner { get; set; }
        public string SupplierName { get; set; }
        public int? SupplierPartner { get; set; }
        public int? Supplier { get; set; }
        public bool? FiscalInvoice { get; set; }
        public int? PaymentMethod { get; set; }
        public DateTime? DueDate { get; set; }
        public decimal? PaymentAmount { get; set; }
        public int? CurrencyPaymentAmount { get; set; }
        public string SupplierInvoiceNo { get; set; }
        public DateTime? SupplierInvoiceDate { get; set; }
        public bool? Recurrence { get; set; }
        public int? Fee { get; set; }
        public bool? SameWithoutFee { get; set; }
        public string ManagementFee { get; set; }
        public int? CurrencyManagementFee { get; set; }
        public string WireFee { get; set; }
        public int? CurrencyWireFee { get; set; }
        public string AdvenceFee { get; set; }
        public int? CurrencyAdvanceFee { get; set; }
        public string InvoiceNo { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public DateTime? PaymentDate { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCurrency CurrencyAdvanceFeeNavigation { get; set; }
        public virtual CatCurrency CurrencyManagementFeeNavigation { get; set; }
        public virtual CatCurrency CurrencyPaymentAmountNavigation { get; set; }
        public virtual CatCurrency CurrencyWireFeeNavigation { get; set; }
        public virtual RequestPayment RequestPaymentNavigation { get; set; }
        public virtual ConsultantContactsService SupplierNavigation { get; set; }
        public virtual SupplierPartnerProfileService SupplierPartnerNavigation { get; set; }
        public virtual ICollection<CommentPaymentConcept> CommentPaymentConcepts { get; set; }
        public virtual ICollection<Concept> Concepts { get; set; }
        public virtual ICollection<DocumentPaymentConcept> DocumentPaymentConcepts { get; set; }
        public virtual ICollection<RecurrencePaymentConcept> RecurrencePaymentConcepts { get; set; }
        public virtual ICollection<WireTransferPaymentConcept> WireTransferPaymentConcepts { get; set; }
        public virtual ICollection<WireTransferServicePaymentConcept> WireTransferServicePaymentConcepts { get; set; }
    }
}