// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class PermanentHome
    {
        public int Id { get; set; }
        public int? HomeFindingId { get; set; }
        public int? PorpertyNo { get; set; }
        public int? PropertyType { get; set; }
        public int? Beds { get; set; }
        public int? Baths { get; set; }
        public string Address { get; set; }
        public string WebSite { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatProperty PorpertyNoNavigation { get; set; }
        public virtual CatPropertyTypeHousing PropertyTypeNavigation { get; set; }
    }
}