// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Permission
    {
        public int Id { get; set; }
        public int? Role { get; set; }
        public int? IdCatMenu { get; set; }
        public int? IdCatSubMenu { get; set; }
        public int? IdCatSeccion { get; set; }
        public bool? Reading { get; set; }
        public bool? Writing { get; set; }
        public bool? Editing { get; set; }
        public bool? Deleting { get; set; }
        public bool? Show { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatMenu IdCatMenuNavigation { get; set; }
        public virtual CatSection IdCatSeccionNavigation { get; set; }
        public virtual CatSubMenu IdCatSubMenuNavigation { get; set; }
        public virtual CatRole RoleNavigation { get; set; }
    }
}