// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class PersonalInformation
    {
        public PersonalInformation()
        {
            CompesationBenefits = new HashSet<CompesationBenefit>();
            EmergencyContacts = new HashSet<EmergencyContact>();
            PaymentInformationProfiles = new HashSet<PaymentInformationProfile>();
        }

        public int Id { get; set; }
        public int? Country { get; set; }
        public int? City { get; set; }
        public string HobbiesPassions { get; set; }
        public string CurrentAddress { get; set; }
        public int? ZipCode { get; set; }
        public DateTime? DateBirth { get; set; }
        public string Nationality { get; set; }
        public string PersonalEmail { get; set; }
        public string PersonalPhone { get; set; }
        public string Allergies { get; set; }
        public string School { get; set; }
        public string Major { get; set; }
        public DateTime? Graduation { get; set; }
        public decimal? TotalCompesation { get; set; }
        public string RhComments { get; set; }
        public string GeneralComments { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCity CityNavigation { get; set; }
        public virtual CatCountry CountryNavigation { get; set; }
        public virtual ProfileUser IdNavigation { get; set; }
        public virtual ICollection<CompesationBenefit> CompesationBenefits { get; set; }
        public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; }
        public virtual ICollection<PaymentInformationProfile> PaymentInformationProfiles { get; set; }
    }
}