// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class PhotoCityEmergency
    {
        public int Id { get; set; }
        public int IdEmergencyAbout { get; set; }
        public string FileName { get; set; }
        public string FileRequest { get; set; }
        public DateTime CreateDate { get; set; }

        public virtual CityEmergency IdEmergencyAboutNavigation { get; set; }
    }
}