// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class PhotosVehicleConsultant
    {
        public int Id { get; set; }
        public int? VehicleConsultant { get; set; }
        public string Photo { get; set; }
        public bool? Interior { get; set; }
        public bool? Exterior { get; set; }
        public bool? Safety { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual VehicleConsultant VehicleConsultantNavigation { get; set; }
    }
}