// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ProfileUser
    {
        public ProfileUser()
        {
            AssignedTeamAssignedByNavigations = new HashSet<AssignedTeam>();
            AssignedTeamAssignedToNavigations = new HashSet<AssignedTeam>();
            CalendarConsultantContactsConsultants = new HashSet<CalendarConsultantContactsConsultant>();
            CountryServices = new HashSet<CountryService>();
            DocumentConsultantContactsConsultants = new HashSet<DocumentConsultantContactsConsultant>();
            ExperienceSurveySuppliers = new HashSet<ExperienceSurveySupplier>();
            ImmigrationCoodinators = new HashSet<ImmigrationCoodinator>();
            ImmigrationSupplierPartners = new HashSet<ImmigrationSupplierPartner>();
            LanguagesConsultantContactsConsultants = new HashSet<LanguagesConsultantContactsConsultant>();
            MapIts = new HashSet<MapIt>();
            Offices = new HashSet<Office>();
            OperationLeaderConsultantNavigations = new HashSet<OperationLeader>();
            OperationLeaderCreatedByNavigations = new HashSet<OperationLeader>();
            RelocationCoordinators = new HashSet<RelocationCoordinator>();
            RelocationSupplierPartners = new HashSet<RelocationSupplierPartner>();
            UnavailableDays = new HashSet<UnavailableDay>();
            VehicleConsultants = new HashSet<VehicleConsultant>();
        }

        public int Id { get; set; }
        public int? AreasCoverage { get; set; }
        public string Photo { get; set; }
        public int? SupplierType { get; set; }
        public int? ResponsablePremierOffice { get; set; }
        public bool? Immigration { get; set; }
        public bool? Relocation { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string MotherLastName { get; set; }
        public int? Title { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int? City { get; set; }
        public int? Country { get; set; }
        public string Comments { get; set; }
        public string ProfessionalBiography { get; set; }
        public int? UserId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual AreasCoverageConsultant AreasCoverageNavigation { get; set; }
        public virtual CatCity CityNavigation { get; set; }
        public virtual CatCountry CountryNavigation { get; set; }
        public virtual CatOffice ResponsablePremierOfficeNavigation { get; set; }
        public virtual CatSupplierType SupplierTypeNavigation { get; set; }
        public virtual CatTitle TitleNavigation { get; set; }
        public virtual User User { get; set; }
        public virtual PersonalInformation PersonalInformation { get; set; }
        public virtual ICollection<AssignedTeam> AssignedTeamAssignedByNavigations { get; set; }
        public virtual ICollection<AssignedTeam> AssignedTeamAssignedToNavigations { get; set; }
        public virtual ICollection<CalendarConsultantContactsConsultant> CalendarConsultantContactsConsultants { get; set; }
        public virtual ICollection<CountryService> CountryServices { get; set; }
        public virtual ICollection<DocumentConsultantContactsConsultant> DocumentConsultantContactsConsultants { get; set; }
        public virtual ICollection<ExperienceSurveySupplier> ExperienceSurveySuppliers { get; set; }
        public virtual ICollection<ImmigrationCoodinator> ImmigrationCoodinators { get; set; }
        public virtual ICollection<ImmigrationSupplierPartner> ImmigrationSupplierPartners { get; set; }
        public virtual ICollection<LanguagesConsultantContactsConsultant> LanguagesConsultantContactsConsultants { get; set; }
        public virtual ICollection<MapIt> MapIts { get; set; }
        public virtual ICollection<Office> Offices { get; set; }
        public virtual ICollection<OperationLeader> OperationLeaderConsultantNavigations { get; set; }
        public virtual ICollection<OperationLeader> OperationLeaderCreatedByNavigations { get; set; }
        public virtual ICollection<RelocationCoordinator> RelocationCoordinators { get; set; }
        public virtual ICollection<RelocationSupplierPartner> RelocationSupplierPartners { get; set; }
        public virtual ICollection<UnavailableDay> UnavailableDays { get; set; }
        public virtual ICollection<VehicleConsultant> VehicleConsultants { get; set; }
    }
}