// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class PropertyManagement
    {
        public PropertyManagement()
        {
            CommentPropertyManagements = new HashSet<CommentPropertyManagement>();
            DocumentPropertyManagements = new HashSet<DocumentPropertyManagement>();
            DocumentReportIssuePropertyManagements = new HashSet<DocumentReportIssuePropertyManagement>();
            PhotoBillPropertyManagements = new HashSet<PhotoBillPropertyManagement>();
            PhotoInspectionPropertyManagements = new HashSet<PhotoInspectionPropertyManagement>();
            PhotoMailPropertyManagements = new HashSet<PhotoMailPropertyManagement>();
            PhotoPropertyManagements = new HashSet<PhotoPropertyManagement>();
            PhotoReportIssuePropertyManagements = new HashSet<PhotoReportIssuePropertyManagement>();
            ReminderPropertyManagements = new HashSet<ReminderPropertyManagement>();
            VisitReportPropertyManagements = new HashSet<VisitReportPropertyManagement>();
        }

        public int Id { get; set; }
        public int? WorkOrderServices { get; set; }
        public bool? Coordination { get; set; }
        public DateTime? AuthoDate { get; set; }
        public DateTime? AuthoAcceptanceDate { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public int? StatusId { get; set; }
        public string PropertAddress { get; set; }
        public int? Library { get; set; }
        public bool? Vacant { get; set; }
        public bool? Rented { get; set; }
        public string Marketing { get; set; }
        public string Links { get; set; }
        public DateTime? UpcommingVisit { get; set; }
        public int? CountVisit { get; set; }
        public string OfferReceived { get; set; }
        public string Submit { get; set; }
        public int? OfferApprovedTenantSelected { get; set; }
        public string LeaseNegotiation { get; set; }
        public string SendDraft { get; set; }
        public string Comments { get; set; }
        public string SignatureCoordination { get; set; }
        public int? LibraryPaymentCoordination { get; set; }
        public string TenancySupport { get; set; }
        public string CommentsQuestion { get; set; }
        public DateTime? LastPropertyInspection { get; set; }
        public string Report { get; set; }
        public DateTime? NextPropertyInspection { get; set; }
        public int? ItemOngoingMaintanance { get; set; }
        public int? ProviderVisit { get; set; }
        public int? ProviderPayment { get; set; }
        public int? BillType { get; set; }
        public string CommentBill { get; set; }
        public int? ProviderPaymentBill { get; set; }
        public string CommentMail { get; set; }
        public int? Severity { get; set; }
        public string DescriptionReportIssue { get; set; }
        public int? StatusReportIssue { get; set; }
        public DateTime? QuoteApproval { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatBillType BillTypeNavigation { get; set; }
        public virtual CatLibrary LibraryNavigation { get; set; }
        public virtual CatSeverity SeverityNavigation { get; set; }
        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual CatStatusReportIssue StatusReportIssueNavigation { get; set; }
        public virtual WorkOrderService WorkOrderServicesNavigation { get; set; }
        public virtual ICollection<CommentPropertyManagement> CommentPropertyManagements { get; set; }
        public virtual ICollection<DocumentPropertyManagement> DocumentPropertyManagements { get; set; }
        public virtual ICollection<DocumentReportIssuePropertyManagement> DocumentReportIssuePropertyManagements { get; set; }
        public virtual ICollection<PhotoBillPropertyManagement> PhotoBillPropertyManagements { get; set; }
        public virtual ICollection<PhotoInspectionPropertyManagement> PhotoInspectionPropertyManagements { get; set; }
        public virtual ICollection<PhotoMailPropertyManagement> PhotoMailPropertyManagements { get; set; }
        public virtual ICollection<PhotoPropertyManagement> PhotoPropertyManagements { get; set; }
        public virtual ICollection<PhotoReportIssuePropertyManagement> PhotoReportIssuePropertyManagements { get; set; }
        public virtual ICollection<ReminderPropertyManagement> ReminderPropertyManagements { get; set; }
        public virtual ICollection<VisitReportPropertyManagement> VisitReportPropertyManagements { get; set; }
    }
}