// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class PropertyReportSection
    {
        public PropertyReportSection()
        {
            PhotosPropertyReportSections = new HashSet<PhotosPropertyReportSection>();
            SectionInventories = new HashSet<SectionInventory>();
        }

        public int Id { get; set; }
        public int? PropertyReport { get; set; }
        public int? PropertySection { get; set; }
        public int? Status { get; set; }
        public bool? NeedRepair { get; set; }
        public DateTime? ReportDate { get; set; }
        public string ReportDetails { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual PropertyReport PropertyReportNavigation { get; set; }
        public virtual CatPropertySection PropertySectionNavigation { get; set; }
        public virtual CatStatusPropertySection StatusNavigation { get; set; }
        public virtual ICollection<PhotosPropertyReportSection> PhotosPropertyReportSections { get; set; }
        public virtual ICollection<SectionInventory> SectionInventories { get; set; }
    }
}