// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class RecurrenceRequestPayment
    {
        public RecurrenceRequestPayment()
        {
            RepeatTheRecurrenceRequestPayments = new HashSet<RepeatTheRecurrenceRequestPayment>();
        }

        public int Id { get; set; }
        public int? RequestPayment { get; set; }
        public int? RepeatEvery { get; set; }
        public int? Period { get; set; }
        public DateTime? StartDate { get; set; }
        public bool? Never { get; set; }
        public bool? Date { get; set; }
        public DateTime? EndDate { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatDuration PeriodNavigation { get; set; }
        public virtual RequestPayment RequestPaymentNavigation { get; set; }
        public virtual ICollection<RepeatTheRecurrenceRequestPayment> RepeatTheRecurrenceRequestPayments { get; set; }
    }
}