// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class RelHousingAmenitie
    {
        public int HousingSpecificationId { get; set; }
        public int AmenitieId { get; set; }

        public virtual CatAmenitie Amenitie { get; set; }
        public virtual HousingSpecification HousingSpecification { get; set; }
    }
}