// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class RelocationSupplierPartner
    {
        public RelocationSupplierPartner()
        {
            AssignedServiceSupliers = new HashSet<AssignedServiceSuplier>();
        }

        public int Id { get; set; }
        public int? SupplierTypeId { get; set; }
        public int? SupplierCompanyId { get; set; }
        public DateTime? AssignedDate { get; set; }
        public DateTime? AcceptedDate { get; set; }
        public int? ServiceRecordId { get; set; }
        public int? SupplierId { get; set; }
        public int? StatusId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ServiceRecord ServiceRecord { get; set; }
        public virtual CatStatusSupplierCoordinator Status { get; set; }
        public virtual ProfileUser Supplier { get; set; }
        public virtual SupplierPartnerProfileConsultant SupplierCompany { get; set; }
        public virtual CatCountry SupplierType { get; set; }
        public virtual ICollection<AssignedServiceSuplier> AssignedServiceSupliers { get; set; }
    }
}