// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ReminderLeaseRenewal
    {
        public int Id { get; set; }
        public int LeaseRenewal { get; set; }
        public DateTime ReminderDate { get; set; }
        public string ReminderComments { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }

        public virtual LeaseRenewal LeaseRenewalNavigation { get; set; }
    }
}