// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class RenewalDetail
    {
        public int Id { get; set; }
        public int? HomeFindingId { get; set; }
        public bool? AutomaticallyRenewal { get; set; }
        public bool? RenewalNotification { get; set; }
        public DateTime? AdditionalRent { get; set; }
    }
}