// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class RenewalDetailHome
    {
        public int Id { get; set; }
        public bool? Automatically { get; set; }
        public bool? RenewalNotification { get; set; }
        public DateTime? AdditionalRentIncreaseDate { get; set; }
        public string RecurrentIncreasePeriod { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual HousingList IdNavigation { get; set; }
    }
}