// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class RentalFurnitureCoordination
    {
        public RentalFurnitureCoordination()
        {
            CommentRentalFurnitureCoordinations = new HashSet<CommentRentalFurnitureCoordination>();
            DocumentRentalFurnitureCoordinations = new HashSet<DocumentRentalFurnitureCoordination>();
            ExtensionRentalFurnitureCoordinations = new HashSet<ExtensionRentalFurnitureCoordination>();
            PaymentsRentalFurnitureCoordinations = new HashSet<PaymentsRentalFurnitureCoordination>();
            ReminderRentalFurnitureCoordinations = new HashSet<ReminderRentalFurnitureCoordination>();
            StayExtensionRentalFurnitureCoordinations = new HashSet<StayExtensionRentalFurnitureCoordination>();
        }

        public int Id { get; set; }
        public int WorkOrderServicesId { get; set; }
        public DateTime AuthoDate { get; set; }
        public DateTime AuthoAcceptanceDate { get; set; }
        public bool? Coordination { get; set; }
        public int? DeliveredTo { get; set; }
        public int StatusId { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public int? TotalTimeAllowed { get; set; }
        public int? TotalTimeAllowedId { get; set; }
        public decimal? Budget { get; set; }
        public int? Currency { get; set; }
        public int? Baths { get; set; }
        public int? Beds { get; set; }
        public int? FamilyMembers { get; set; }
        public int? PaymentResponsibility { get; set; }
        public int? SupplierPartner { get; set; }
        public int? MainContact { get; set; }
        public DateTime? DeliveredDate { get; set; }
        public DateTime? ScheduledPickUpDate { get; set; }
        public int? TotalDays { get; set; }
        public int? DeliverTo { get; set; }
        public string PropertyAddress { get; set; }
        public decimal? RentalAmount { get; set; }
        public int? CurrencyExtension { get; set; }
        public decimal? SecurityDeposit { get; set; }
        public decimal? PaymentDue { get; set; }
        public int? ReturnSecurityDeposit { get; set; }
        public string Comments { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCurrency CurrencyExtensionNavigation { get; set; }
        public virtual CatCurrency CurrencyNavigation { get; set; }
        public virtual AdministrativeContactsService MainContactNavigation { get; set; }
        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual SupplierPartnerProfileService SupplierPartnerNavigation { get; set; }
        public virtual CatDuration TotalTimeAllowedNavigation { get; set; }
        public virtual WorkOrderService WorkOrderServices { get; set; }
        public virtual ICollection<CommentRentalFurnitureCoordination> CommentRentalFurnitureCoordinations { get; set; }
        public virtual ICollection<DocumentRentalFurnitureCoordination> DocumentRentalFurnitureCoordinations { get; set; }
        public virtual ICollection<ExtensionRentalFurnitureCoordination> ExtensionRentalFurnitureCoordinations { get; set; }
        public virtual ICollection<PaymentsRentalFurnitureCoordination> PaymentsRentalFurnitureCoordinations { get; set; }
        public virtual ICollection<ReminderRentalFurnitureCoordination> ReminderRentalFurnitureCoordinations { get; set; }
        public virtual ICollection<StayExtensionRentalFurnitureCoordination> StayExtensionRentalFurnitureCoordinations { get; set; }
    }
}