// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ReportAnEvent
    {
        public ReportAnEvent()
        {
            AssignedPhotos = new HashSet<AssignedPhoto>();
            CommentReportAnEvents = new HashSet<CommentReportAnEvent>();
            SupplierConsultantPhotos = new HashSet<SupplierConsultantPhoto>();
        }

        public int Id { get; set; }
        public int TenancyManagementId { get; set; }
        public DateTime? EventReportDate { get; set; }
        public DateTime? EventCloseDate { get; set; }
        public int? SeverityId { get; set; }
        public string Description { get; set; }
        public int? StatusId { get; set; }
        public int? EventId { get; set; }
        public string QuoteApproval { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatEvent Event { get; set; }
        public virtual CatSeverity Severity { get; set; }
        public virtual CatStatusReportAnEvent Status { get; set; }
        public virtual TenancyManagement TenancyManagement { get; set; }
        public virtual ICollection<AssignedPhoto> AssignedPhotos { get; set; }
        public virtual ICollection<CommentReportAnEvent> CommentReportAnEvents { get; set; }
        public virtual ICollection<SupplierConsultantPhoto> SupplierConsultantPhotos { get; set; }
    }
}