// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class RequestInformation
    {
        public RequestInformation()
        {
            RequestInformationDocuments = new HashSet<RequestInformationDocument>();
        }

        public int Id { get; set; }
        public string SentTo { get; set; }
        public int? AuthorizedBy { get; set; }
        public bool? NeedsAssessment { get; set; }
        public bool? ImmigrationProfile { get; set; }
        public bool? HousingSpecification { get; set; }
        public int? House { get; set; }
        public int? ServiceRecordId { get; set; }
        public DateTime? Due { get; set; }

        public virtual User AuthorizedByNavigation { get; set; }
        public virtual ServiceRecord ServiceRecord { get; set; }
        public virtual ICollection<RequestInformationDocument> RequestInformationDocuments { get; set; }
    }
}