// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class RequestPayment
    {
        public RequestPayment()
        {
            CommentRequestPayments = new HashSet<CommentRequestPayment>();
            DocumentRequestPayments = new HashSet<DocumentRequestPayment>();
            Payments = new HashSet<Payment>();
            RecurrenceRequestPayments = new HashSet<RecurrenceRequestPayment>();
        }

        public int Id { get; set; }
        public int? WorkOrderServicesId { get; set; }
        public string Title { get; set; }
        public int? Status { get; set; }
        public int? Country { get; set; }
        public int? City { get; set; }
        public string Description { get; set; }
        public bool? Urgent { get; set; }
        public bool? Recurrence { get; set; }
        public DateTime? FundingRequestDate { get; set; }
        public string InvoiceNo { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public DateTime? PaymentDate { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCity CityNavigation { get; set; }
        public virtual CatCountry CountryNavigation { get; set; }
        public virtual CatRequestPaymentStatus StatusNavigation { get; set; }
        public virtual WorkOrderService WorkOrderServices { get; set; }
        public virtual ICollection<CommentRequestPayment> CommentRequestPayments { get; set; }
        public virtual ICollection<DocumentRequestPayment> DocumentRequestPayments { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<RecurrenceRequestPayment> RecurrenceRequestPayments { get; set; }
    }
}