// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ScalateService
    {
        public ScalateService()
        {
            ScalateComments = new HashSet<ScalateComment>();
            ScalateDocuments = new HashSet<ScalateDocument>();
        }

        public int Id { get; set; }
        public int? UserToId { get; set; }
        public int? UserFromId { get; set; }
        public bool? Status { get; set; }
        public int? EscalationLevel { get; set; }
        public int? WorkOrderId { get; set; }
        public int? ServiceId { get; set; }
        public int? ServiceLineId { get; set; }
        public DateTime? Escalation { get; set; }
        public int? ServiceRecordId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ClosedDate { get; set; }

        public virtual CatServiceLine ServiceLine { get; set; }
        public virtual User UserFrom { get; set; }
        public virtual User UserTo { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual ICollection<ScalateComment> ScalateComments { get; set; }
        public virtual ICollection<ScalateDocument> ScalateDocuments { get; set; }
    }
}