// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class SchoolsList
    {
        public SchoolsList()
        {
            SchoolingReports = new HashSet<SchoolingReport>();
        }

        public int Id { get; set; }
        public int? WorkOrder { get; set; }
        public int? Service { get; set; }
        public int? ServiceType { get; set; }
        public int? SchoolNo { get; set; }
        public DateTime? VisitDate { get; set; }
        public int? SchoolingStatus { get; set; }
        public int? Dependent { get; set; }
        public string SchoolName { get; set; }
        public int? Country { get; set; }
        public int? City { get; set; }
        public string Address { get; set; }
        public int? Grade { get; set; }
        public int? Languages { get; set; }
        public string WebSite { get; set; }
        public bool? Ib { get; set; }
        public bool? Uniform { get; set; }
        public bool? MedicalRecordNeeded { get; set; }
        public string Admision { get; set; }
        public decimal? PerMonth { get; set; }
        public decimal? ForEnrollment { get; set; }
        public decimal? FeesEnrollment { get; set; }
        public int? Currency { get; set; }
        public string AdditionalComments { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCity CityNavigation { get; set; }
        public virtual CatCountry CountryNavigation { get; set; }
        public virtual CatCurrency CurrencyNavigation { get; set; }
        public virtual DependentInformation DependentNavigation { get; set; }
        public virtual CatGradeSchooling GradeNavigation { get; set; }
        public virtual CatLanguage LanguagesNavigation { get; set; }
        public virtual CatSchoolStatus SchoolingStatusNavigation { get; set; }
        public virtual WorkOrder WorkOrderNavigation { get; set; }
        public virtual ICollection<SchoolingReport> SchoolingReports { get; set; }
    }
}