// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Schooling
    {
        public int Id { get; set; }
        public int? RelationshipId { get; set; }
        public string Avatar { get; set; }
        public string Name { get; set; }
        public DateTime? Birth { get; set; }
        public int? Age { get; set; }
        public int? Sex { get; set; }
        public int? LanguagesSpoken { get; set; }
        public int? Nationality { get; set; }
        public int? CurrentGrade { get; set; }
        public string Comments { get; set; }
        public int? PredecisionOrientationId { get; set; }
        public bool? Active { get; set; }

        public virtual CatGradeSchooling CurrentGradeNavigation { get; set; }
        public virtual CatLanguage LanguagesSpokenNavigation { get; set; }
        public virtual CatCountry NationalityNavigation { get; set; }
        public virtual PredecisionOrientation PredecisionOrientation { get; set; }
        public virtual DependentInformation Relationship { get; set; }
    }
}