// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class SectionInventory
    {
        public SectionInventory()
        {
            PhotosInventories = new HashSet<PhotosInventory>();
        }

        public int Id { get; set; }
        public int? PropertyReportSectionId { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public int? Quantity { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual PropertyReportSection PropertyReportSection { get; set; }
        public virtual ICollection<PhotosInventory> PhotosInventories { get; set; }
    }
}