// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ServiceScoreAward
    {
        public int Id { get; set; }
        public int IdClientPartnerProfile { get; set; }
        public int IdType { get; set; }
        public string Description { get; set; }
        public int IdServiceLine { get; set; }
        public DateTime Year { get; set; }
        public string Comment { get; set; }

        public virtual ClientPartnerProfile IdClientPartnerProfileNavigation { get; set; }
        public virtual CatServiceLine IdServiceLineNavigation { get; set; }
        public virtual CatType IdType1 { get; set; }
        public virtual CatServiceScoreAward IdTypeNavigation { get; set; }
    }
}