// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ServiceLocationCountry
    {
        public ServiceLocationCountry()
        {
            DocumentLocationCountries = new HashSet<DocumentLocationCountry>();
        }

        public int Id { get; set; }
        public int IdServiceLocation { get; set; }
        public int IdCountry { get; set; }
        public long StandarScopeDocuments { get; set; }
        public string ScopeDescription { get; set; }

        public virtual CatCountry IdCountryNavigation { get; set; }
        public virtual ServiceLocation IdServiceLocationNavigation { get; set; }
        public virtual ICollection<DocumentLocationCountry> DocumentLocationCountries { get; set; }
    }
}