// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Service
    {
        public Service()
        {
            ServiceCountries = new HashSet<ServiceCountry>();
        }

        public int Id { get; set; }
        public int? Service1 { get; set; }
        public int? ServiceLine { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatService Service1Navigation { get; set; }
        public virtual CatServiceLine ServiceLineNavigation { get; set; }
        public virtual ICollection<ServiceCountry> ServiceCountries { get; set; }
    }
}