// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ServiceCountry
    {
        public ServiceCountry()
        {
            DocumentServiceCountries = new HashSet<DocumentServiceCountry>();
        }

        public int Id { get; set; }
        public int? Service { get; set; }
        public int? Country { get; set; }
        public string ScopeDescription { get; set; }
        public string ScopeTitle { get; set; }
        public bool? ScopeDocuments { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCountry CountryNavigation { get; set; }
        public virtual Service ServiceNavigation { get; set; }
        public virtual ICollection<DocumentServiceCountry> DocumentServiceCountries { get; set; }
    }
}