// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class ServiceInvoice
    {
        public int Id { get; set; }
        public int? Invoice { get; set; }
        public int? WorkOrder { get; set; }
        public int? Service { get; set; }
        public int? ServiceLine { get; set; }
        public int? TypeService { get; set; }
        public int? Status { get; set; }
        public DateTime? DueDate { get; set; }
        public bool? ToInvoice { get; set; }
        public string HourInvoice { get; set; }
        public decimal? AmountToInvoice { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual Invoice InvoiceNavigation { get; set; }
        public virtual CatStatusInvoice StatusNavigation { get; set; }
        public virtual WorkOrder WorkOrderNavigation { get; set; }
    }
}