// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class SettlingIn
    {
        public SettlingIn()
        {
            CommentSettlingIns = new HashSet<CommentSettlingIn>();
            DocumentSettlingIns = new HashSet<DocumentSettlingIn>();
            ExtensionSettlingIns = new HashSet<ExtensionSettlingIn>();
            ReminderSettlingIns = new HashSet<ReminderSettlingIn>();
        }

        public int Id { get; set; }
        public int WorkOrderServicesId { get; set; }
        public DateTime AuthoDate { get; set; }
        public DateTime AuthoAcceptanceDate { get; set; }
        public bool? Coordination { get; set; }
        public int StatusId { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public bool? BankAccount { get; set; }
        public string BankName { get; set; }
        public DateTime? BankCompleted { get; set; }
        public bool? CarPurchaseLease { get; set; }
        public DateTime? CarCompleted { get; set; }
        public bool? DriverLicense { get; set; }
        public DateTime? DriverLicenseCompleted { get; set; }
        public bool? CleaningServices { get; set; }
        public DateTime? CleaningServicesCompleted { get; set; }
        public int? CleaningServicesSupplierPartner { get; set; }
        public string CleaningServicesSupplier { get; set; }
        public bool? ChildCare { get; set; }
        public DateTime? ChildCareCompleted { get; set; }
        public int? ChildCareSupplierPartner { get; set; }
        public string ChildCareSupplier { get; set; }
        public bool? RecreationalClub { get; set; }
        public DateTime? RecreationalClubCompleted { get; set; }
        public bool? HealthCare { get; set; }
        public DateTime? HealthCareCompleted { get; set; }
        public bool? LeisureClubMembership { get; set; }
        public DateTime? LeisureClubMembershipCompleted { get; set; }
        public bool? LocalRegistration { get; set; }
        public DateTime? LocalRegistrationCompleted { get; set; }
        public bool? SpousalAssistance { get; set; }
        public DateTime? SpousalAssistanceCompleted { get; set; }
        public string Comment { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual SupplierPartnerProfileService ChildCareSupplierPartnerNavigation { get; set; }
        public virtual SupplierPartnerProfileService CleaningServicesSupplierPartnerNavigation { get; set; }
        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual WorkOrderService WorkOrderServices { get; set; }
        public virtual ICollection<CommentSettlingIn> CommentSettlingIns { get; set; }
        public virtual ICollection<DocumentSettlingIn> DocumentSettlingIns { get; set; }
        public virtual ICollection<ExtensionSettlingIn> ExtensionSettlingIns { get; set; }
        public virtual ICollection<ReminderSettlingIn> ReminderSettlingIns { get; set; }
    }
}