// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class SupplierPartnerProfileConsultant
    {
        public SupplierPartnerProfileConsultant()
        {
            AreasCoverageConsultants = new HashSet<AreasCoverageConsultant>();
            ImmigrationSupplierPartners = new HashSet<ImmigrationSupplierPartner>();
            RelocationSupplierPartners = new HashSet<RelocationSupplierPartner>();
        }

        public int Id { get; set; }
        public int? Type { get; set; }
        public string Photo { get; set; }
        public int? Status { get; set; }
        public bool? Immigration { get; set; }
        public bool? Relocation { get; set; }
        public string ComercialName { get; set; }
        public string LegalName { get; set; }
        public bool? LuxuryVip { get; set; }
        public DateTime? SupplierSince { get; set; }
        public string About { get; set; }
        public decimal? AmountPerHour { get; set; }
        public int? Currency { get; set; }
        public int? CreditTerms { get; set; }
        public int? TaxesPercentage { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCreditTerm CreditTermsNavigation { get; set; }
        public virtual CatCurrency CurrencyNavigation { get; set; }
        public virtual CatSupplierPartnerProfileStatus StatusNavigation { get; set; }
        public virtual CatTaxePercentage TaxesPercentageNavigation { get; set; }
        public virtual CatSupplierPartnerProfileType TypeNavigation { get; set; }
        public virtual ICollection<AreasCoverageConsultant> AreasCoverageConsultants { get; set; }
        public virtual ICollection<ImmigrationSupplierPartner> ImmigrationSupplierPartners { get; set; }
        public virtual ICollection<RelocationSupplierPartner> RelocationSupplierPartners { get; set; }
    }
}