// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class SupplierPartnerProfileService
    {
        public SupplierPartnerProfileService()
        {
            AirportTransportationServices = new HashSet<AirportTransportationService>();
            AreasCoverageServices = new HashSet<AreasCoverageService>();
            HomeFindings = new HashSet<HomeFinding>();
            HousingLists = new HashSet<HousingList>();
            Payments = new HashSet<Payment>();
            RentalFurnitureCoordinations = new HashSet<RentalFurnitureCoordination>();
            SettlingInChildCareSupplierPartnerNavigations = new HashSet<SettlingIn>();
            SettlingInCleaningServicesSupplierPartnerNavigations = new HashSet<SettlingIn>();
            SupplierPartnerDetails = new HashSet<SupplierPartnerDetail>();
        }

        public int Id { get; set; }
        public int? Type { get; set; }
        public string Photo { get; set; }
        public int? Status { get; set; }
        public int? ServiceLine { get; set; }
        public bool? Immigration { get; set; }
        public bool? Relocation { get; set; }
        public int? SupplierType { get; set; }
        public string ComercialName { get; set; }
        public string LegalName { get; set; }
        public bool? LuxuryVip { get; set; }
        public DateTime? SupplierSince { get; set; }
        public string About { get; set; }
        public decimal? AmountPerHour { get; set; }
        public int? Currency { get; set; }
        public int? CreditTerms { get; set; }
        public int? TaxesPercentage { get; set; }
        public string TaxeName { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCreditTerm CreditTermsNavigation { get; set; }
        public virtual CatCurrency CurrencyNavigation { get; set; }
        public virtual CatServiceLine ServiceLineNavigation { get; set; }
        public virtual CatSupplierPartnerProfileStatus StatusNavigation { get; set; }
        public virtual CatSupplierType SupplierTypeNavigation { get; set; }
        public virtual CatTaxePercentage TaxesPercentageNavigation { get; set; }
        public virtual CatSupplierPartnerProfileType TypeNavigation { get; set; }
        public virtual ICollection<AirportTransportationService> AirportTransportationServices { get; set; }
        public virtual ICollection<AreasCoverageService> AreasCoverageServices { get; set; }
        public virtual ICollection<HomeFinding> HomeFindings { get; set; }
        public virtual ICollection<HousingList> HousingLists { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<RentalFurnitureCoordination> RentalFurnitureCoordinations { get; set; }
        public virtual ICollection<SettlingIn> SettlingInChildCareSupplierPartnerNavigations { get; set; }
        public virtual ICollection<SettlingIn> SettlingInCleaningServicesSupplierPartnerNavigations { get; set; }
        public virtual ICollection<SupplierPartnerDetail> SupplierPartnerDetails { get; set; }
    }
}