// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class SupplierPartnerDetail
    {
        public SupplierPartnerDetail()
        {
            TypeVehiclesSupplierPartnerDetails = new HashSet<TypeVehiclesSupplierPartnerDetail>();
        }

        public int Id { get; set; }
        public int? SupplierPartnerProfileService { get; set; }
        public int? FleetSize { get; set; }
        public int? NumberDirvers { get; set; }
        public bool? ArmouredVehicles { get; set; }
        public int? TypeVehicles { get; set; }
        public bool? CarSeatRental { get; set; }
        public string LicenceMlsNumber { get; set; }
        public bool? InsuranceCoverage { get; set; }
        public bool? OnlineSolution { get; set; }
        public bool? FaceFaceAssistance { get; set; }
        public bool? PetFriendly { get; set; }
        public bool? AirportShuttle { get; set; }
        public bool? MealPlans { get; set; }
        public bool? MergencyKits { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual SupplierPartnerProfileService SupplierPartnerProfileServiceNavigation { get; set; }
        public virtual ICollection<TypeVehiclesSupplierPartnerDetail> TypeVehiclesSupplierPartnerDetails { get; set; }
    }
}