// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class SupplierConsultantPhoto
    {
        public int Id { get; set; }
        public int ReportAnEventId { get; set; }
        public string PhotoName { get; set; }
        public string PhotoPath { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ReportAnEvent ReportAnEvent { get; set; }
    }
}