// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Task
    {
        public Task()
        {
            ColaboratorMembers = new HashSet<ColaboratorMember>();
            TaskDocuments = new HashSet<TaskDocument>();
            TaskReplies = new HashSet<TaskReply>();
        }

        public int Id { get; set; }
        public int? ServiceRecordId { get; set; }
        public int? WorkOrderId { get; set; }
        public int? TaskFrom { get; set; }
        public int TaskTo { get; set; }
        public int StatusId { get; set; }
        public DateTime AssignedDate { get; set; }
        public DateTime DueDate { get; set; }
        public DateTime? CompletedDate { get; set; }
        public int? ServiceId { get; set; }
        public int? ServiceLineId { get; set; }
        public string Comments { get; set; }
        public string TaskDescription { get; set; }
        public string ActionTitle { get; set; }
        public bool? OverdueTask { get; set; }
        public int? Department { get; set; }
        public int? ActionType { get; set; }
        public bool? Urgent { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatActionType ActionTypeNavigation { get; set; }
        public virtual CatDepartment DepartmentNavigation { get; set; }
        public virtual WorkOrderService Service { get; set; }
        public virtual CatServiceLine ServiceLine { get; set; }
        public virtual ServiceRecord ServiceRecord { get; set; }
        public virtual TaskStatus Status { get; set; }
        public virtual User TaskFromNavigation { get; set; }
        public virtual User TaskToNavigation { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual ICollection<ColaboratorMember> ColaboratorMembers { get; set; }
        public virtual ICollection<TaskDocument> TaskDocuments { get; set; }
        public virtual ICollection<TaskReply> TaskReplies { get; set; }
    }
}