// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class TaskDocument
    {
        public int Id { get; set; }
        public string FileRequest { get; set; }
        public string NameFile { get; set; }
        public string Comment { get; set; }
        public int TaskId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedBy { get; set; }

        public virtual Task Task { get; set; }
    }
}