// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class TemporaryHousingCoordinaton
    {
        public TemporaryHousingCoordinaton()
        {
            CommentTemporaryHosuings = new HashSet<CommentTemporaryHosuing>();
            DocumentTemporaryHousingCoordinatons = new HashSet<DocumentTemporaryHousingCoordinaton>();
            ExtensionTemporaryHousingCoordinatons = new HashSet<ExtensionTemporaryHousingCoordinaton>();
            ReminderTemporaryHousingCoordinatons = new HashSet<ReminderTemporaryHousingCoordinaton>();
            StayExtensionTemporaryHousings = new HashSet<StayExtensionTemporaryHousing>();
        }

        public int Id { get; set; }
        public int WorkOrderServicesId { get; set; }
        public DateTime AuthoDate { get; set; }
        public DateTime AuthoAcceptanceDate { get; set; }
        public bool? Coordination { get; set; }
        public int StatusId { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public bool? Apartment { get; set; }
        public bool? House { get; set; }
        public int? Bedrooms { get; set; }
        public int? Bathrooms { get; set; }
        public bool? PetFrindly { get; set; }
        public DateTime? TotalAllotedDaysStart { get; set; }
        public DateTime? TotalAllotedDaysEnd { get; set; }
        public decimal? Budget { get; set; }
        public int? Currency { get; set; }
        public int? PaymentResponsibilty { get; set; }
        public bool? ClientSecurityInspectionRequired { get; set; }
        public int? ReservationType { get; set; }
        public int? SupplierPartner { get; set; }
        public int? PropertyNo { get; set; }
        public string PropertyAddress { get; set; }
        public string Neighborhood { get; set; }
        public decimal? FinalReservationAmount { get; set; }
        public int? CurrencyFinalReservationAmount { get; set; }
        public DateTime? CheckIn { get; set; }
        public DateTime? CheckOut { get; set; }
        public decimal? SecurityDeposit { get; set; }
        public int? CurencySecurityDeposit { get; set; }
        public int? PaymentsDue { get; set; }
        public int? TotalDays { get; set; }
        public bool? Extension { get; set; }
        public string Comments { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual ConsultantContactsService SupplierPartnerNavigation { get; set; }
        public virtual WorkOrderService WorkOrderServices { get; set; }
        public virtual ICollection<CommentTemporaryHosuing> CommentTemporaryHosuings { get; set; }
        public virtual ICollection<DocumentTemporaryHousingCoordinaton> DocumentTemporaryHousingCoordinatons { get; set; }
        public virtual ICollection<ExtensionTemporaryHousingCoordinaton> ExtensionTemporaryHousingCoordinatons { get; set; }
        public virtual ICollection<ReminderTemporaryHousingCoordinaton> ReminderTemporaryHousingCoordinatons { get; set; }
        public virtual ICollection<StayExtensionTemporaryHousing> StayExtensionTemporaryHousings { get; set; }
    }
}