// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class TenancyManagement
    {
        public TenancyManagement()
        {
            CommentTenancyManagements = new HashSet<CommentTenancyManagement>();
            DocumentTenancyManagements = new HashSet<DocumentTenancyManagement>();
            ReminderTenancyManagements = new HashSet<ReminderTenancyManagement>();
            ReportAnEvents = new HashSet<ReportAnEvent>();
        }

        public int Id { get; set; }
        public int? WorkOrderServices { get; set; }
        public bool? Coordination { get; set; }
        public DateTime? AuthoDate { get; set; }
        public DateTime? AuthoAcceptanceDate { get; set; }
        public int? DeliverTo { get; set; }
        public int? StatusId { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public DateTime? Recurrence { get; set; }
        public DateTime? MonthlyFollowUp { get; set; }
        public int? PropertyId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual DependentInformation DeliverToNavigation { get; set; }
        public virtual HousingList Property { get; set; }
        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual WorkOrderService WorkOrderServicesNavigation { get; set; }
        public virtual ICollection<CommentTenancyManagement> CommentTenancyManagements { get; set; }
        public virtual ICollection<DocumentTenancyManagement> DocumentTenancyManagements { get; set; }
        public virtual ICollection<ReminderTenancyManagement> ReminderTenancyManagements { get; set; }
        public virtual ICollection<ReportAnEvent> ReportAnEvents { get; set; }
    }
}