// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class TermsDeal
    {
        public int Id { get; set; }
        public int IdClientPartnerProfile { get; set; }
        public int IdPrice { get; set; }
        public int? IdCurrency { get; set; }
        public string Volume { get; set; }
        public int Sevices { get; set; }
        public int Amount { get; set; }
        public string Fixed { get; set; }
        public string BussinesUnit { get; set; }

        public virtual ClientPartnerProfile IdClientPartnerProfileNavigation { get; set; }
        public virtual CatCurrency IdCurrencyNavigation { get; set; }
        public virtual CatPriceTermsDeal IdPriceNavigation { get; set; }
    }
}