// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class Theme
    {
        public Theme()
        {
            Files = new HashSet<File>();
        }

        public int Id { get; set; }
        public int Content { get; set; }
        public string Text { get; set; }
        public int? Element { get; set; }
        public string Url { get; set; }
        public int? Order { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual Content ContentNavigation { get; set; }
        public virtual CatElement ElementNavigation { get; set; }
        public virtual ICollection<File> Files { get; set; }
    }
}