// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class training
    {
        public training()
        {
            Contents = new HashSet<Content>();
            Participants = new HashSet<Participant>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public bool Groups { get; set; }
        public int? TrainingGroup { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public int? CreationBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatTrainingGroup TrainingGroupNavigation { get; set; }
        public virtual CatTrainingType TypeNavigation { get; set; }
        public virtual ICollection<Content> Contents { get; set; }
        public virtual ICollection<Participant> Participants { get; set; }
    }
}