// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class TypeOffice
    {
        public TypeOffice()
        {
            OfficeInformations = new HashSet<OfficeInformation>();
        }

        public int Id { get; set; }
        public string Type { get; set; }

        public virtual ICollection<OfficeInformation> OfficeInformations { get; set; }
    }
}