// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class UpcomingEvent
    {
        public int Id { get; set; }
        public DateTime? EventDate { get; set; }
        public string Title { get; set; }
        public int? Country { get; set; }
        public int? City { get; set; }
        public string Description { get; set; }
        public bool? Status { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCity CityNavigation { get; set; }
        public virtual CatCountry CountryNavigation { get; set; }
    }
}