// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class UserGroup
    {
        public int Conversation { get; set; }
        public int UserReciver { get; set; }

        public virtual Conversation ConversationNavigation { get; set; }
        public virtual User UserReciverNavigation { get; set; }
    }
}