// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class VehicleConsultant
    {
        public VehicleConsultant()
        {
            DocumentVehicleConsultants = new HashSet<DocumentVehicleConsultant>();
            PhotosVehicleConsultants = new HashSet<PhotosVehicleConsultant>();
        }

        public int Id { get; set; }
        public int? ConsultantContactsConsultant { get; set; }
        public int? VehicleType { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public int? Year { get; set; }
        public string PlateNumber { get; set; }
        public string Color { get; set; }
        public int? Capacity { get; set; }
        public int? NumberDoor { get; set; }
        public bool? AirConditioner { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ProfileUser ConsultantContactsConsultantNavigation { get; set; }
        public virtual CatVehicleType VehicleTypeNavigation { get; set; }
        public virtual ICollection<DocumentVehicleConsultant> DocumentVehicleConsultants { get; set; }
        public virtual ICollection<PhotosVehicleConsultant> PhotosVehicleConsultants { get; set; }
    }
}