// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class VisaDeregistration
    {
        public VisaDeregistration()
        {
            CommentVisaDeregistrations = new HashSet<CommentVisaDeregistration>();
            DocumentVisaDeregistrations = new HashSet<DocumentVisaDeregistration>();
            ReminderVisaDeregistrations = new HashSet<ReminderVisaDeregistration>();
        }

        public int Id { get; set; }
        public DateTime AuthoDate { get; set; }
        public DateTime AuthoAcceptanceDate { get; set; }
        public int ApplicantId { get; set; }
        public int? StatusId { get; set; }
        public string Name { get; set; }
        public int? WorkOrderServicesId { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public int? HostCountryId { get; set; }
        public int? HostCityId { get; set; }
        public string City { get; set; }
        public string VisaTypeId { get; set; }
        public int? ConsularServiceId { get; set; }
        public DateTime? CountryDepertureDate { get; set; }
        public DateTime? EmploymentLastDay { get; set; }
        public DateTime? DocumentCollectionStartDate { get; set; }
        public DateTime? DocumentCollectionCompletionDate { get; set; }
        public DateTime? DocumentDeliveryDate { get; set; }
        public DateTime? ApplicationSubmissionDate { get; set; }
        public DateTime? DocumentExpirationDate { get; set; }
        public DateTime? ApplicationApprovalDate { get; set; }
        public string Comment { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatCountry HostCountry { get; set; }
        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual WorkOrderService WorkOrderServices { get; set; }
        public virtual ICollection<CommentVisaDeregistration> CommentVisaDeregistrations { get; set; }
        public virtual ICollection<DocumentVisaDeregistration> DocumentVisaDeregistrations { get; set; }
        public virtual ICollection<ReminderVisaDeregistration> ReminderVisaDeregistrations { get; set; }
    }
}