// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class WireTransferServicePaymentConcept
    {
        public int PaymentConcept { get; set; }
        public int WireTransferService { get; set; }

        public virtual Payment PaymentConceptNavigation { get; set; }
        public virtual WireTransferService WireTransferServiceNavigation { get; set; }
    }
}