// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class WorkOrder
    {
        public WorkOrder()
        {
            BundledServicesWorkOrders = new HashSet<BundledServicesWorkOrder>();
            Calls = new HashSet<Call>();
            HousingLists = new HashSet<HousingList>();
            ReportDays = new HashSet<ReportDay>();
            RequestAdditionalTimes = new HashSet<RequestAdditionalTime>();
            ScalateServices = new HashSet<ScalateService>();
            SchoolsLists = new HashSet<SchoolsList>();
            ServiceInvoices = new HashSet<ServiceInvoice>();
            StandaloneServiceWorkOrders = new HashSet<StandaloneServiceWorkOrder>();
            Tasks = new HashSet<Task>();
        }

        public int Id { get; set; }
        public string NumberWorkOrder { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? ServiceLineId { get; set; }
        public int? ServiceRecordId { get; set; }
        public int? StatusId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatServiceLine ServiceLine { get; set; }
        public virtual ServiceRecord ServiceRecord { get; set; }
        public virtual ServiceOrderServicesStatus Status { get; set; }
        public virtual ICollection<BundledServicesWorkOrder> BundledServicesWorkOrders { get; set; }
        public virtual ICollection<Call> Calls { get; set; }
        public virtual ICollection<HousingList> HousingLists { get; set; }
        public virtual ICollection<ReportDay> ReportDays { get; set; }
        public virtual ICollection<RequestAdditionalTime> RequestAdditionalTimes { get; set; }
        public virtual ICollection<ScalateService> ScalateServices { get; set; }
        public virtual ICollection<SchoolsList> SchoolsLists { get; set; }
        public virtual ICollection<ServiceInvoice> ServiceInvoices { get; set; }
        public virtual ICollection<StandaloneServiceWorkOrder> StandaloneServiceWorkOrders { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}