// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class WorkOrderService
    {
        public WorkOrderService()
        {
            AirportTransportationServices = new HashSet<AirportTransportationService>();
            AppointmentWorkOrderServices = new HashSet<AppointmentWorkOrderService>();
            AreaOrientations = new HashSet<AreaOrientation>();
            AssignedServiceSupliers = new HashSet<AssignedServiceSuplier>();
            AssigneeFeedbacks = new HashSet<AssigneeFeedback>();
            BundledServices = new HashSet<BundledService>();
            Calls = new HashSet<Call>();
            CorporateAssistances = new HashSet<CorporateAssistance>();
            Departures = new HashSet<Departure>();
            DocumentManagements = new HashSet<DocumentManagement>();
            EntryVisas = new HashSet<EntryVisa>();
            ExperienceSurveys = new HashSet<ExperienceSurvey>();
            HomeFindings = new HashSet<HomeFinding>();
            HomePurchases = new HashSet<HomePurchase>();
            HomeSales = new HashSet<HomeSale>();
            HousingSpecifications = new HashSet<HousingSpecification>();
            LeaseRenewals = new HashSet<LeaseRenewal>();
            LegalReviews = new HashSet<LegalReview>();
            LocalDocumentations = new HashSet<LocalDocumentation>();
            Notifications = new HashSet<Notification>();
            Others = new HashSet<Other>();
            PredecisionOrientations = new HashSet<PredecisionOrientation>();
            PropertyManagements = new HashSet<PropertyManagement>();
            Renewals = new HashSet<Renewal>();
            RentalFurnitureCoordinations = new HashSet<RentalFurnitureCoordination>();
            RequestPayments = new HashSet<RequestPayment>();
            ResidencyPermits = new HashSet<ResidencyPermit>();
            SchoolingSearches = new HashSet<SchoolingSearch>();
            SettlingIns = new HashSet<SettlingIn>();
            StandaloneServiceWorkOrders = new HashSet<StandaloneServiceWorkOrder>();
            Tasks = new HashSet<Task>();
            TemporaryHousingCoordinatons = new HashSet<TemporaryHousingCoordinaton>();
            TenancyManagements = new HashSet<TenancyManagement>();
            Transportations = new HashSet<Transportation>();
            VisaDeregistrations = new HashSet<VisaDeregistration>();
            WorkPermits = new HashSet<WorkPermit>();
        }

        public int Id { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<AirportTransportationService> AirportTransportationServices { get; set; }
        public virtual ICollection<AppointmentWorkOrderService> AppointmentWorkOrderServices { get; set; }
        public virtual ICollection<AreaOrientation> AreaOrientations { get; set; }
        public virtual ICollection<AssignedServiceSuplier> AssignedServiceSupliers { get; set; }
        public virtual ICollection<AssigneeFeedback> AssigneeFeedbacks { get; set; }
        public virtual ICollection<BundledService> BundledServices { get; set; }
        public virtual ICollection<Call> Calls { get; set; }
        public virtual ICollection<CorporateAssistance> CorporateAssistances { get; set; }
        public virtual ICollection<Departure> Departures { get; set; }
        public virtual ICollection<DocumentManagement> DocumentManagements { get; set; }
        public virtual ICollection<EntryVisa> EntryVisas { get; set; }
        public virtual ICollection<ExperienceSurvey> ExperienceSurveys { get; set; }
        public virtual ICollection<HomeFinding> HomeFindings { get; set; }
        public virtual ICollection<HomePurchase> HomePurchases { get; set; }
        public virtual ICollection<HomeSale> HomeSales { get; set; }
        public virtual ICollection<HousingSpecification> HousingSpecifications { get; set; }
        public virtual ICollection<LeaseRenewal> LeaseRenewals { get; set; }
        public virtual ICollection<LegalReview> LegalReviews { get; set; }
        public virtual ICollection<LocalDocumentation> LocalDocumentations { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Other> Others { get; set; }
        public virtual ICollection<PredecisionOrientation> PredecisionOrientations { get; set; }
        public virtual ICollection<PropertyManagement> PropertyManagements { get; set; }
        public virtual ICollection<Renewal> Renewals { get; set; }
        public virtual ICollection<RentalFurnitureCoordination> RentalFurnitureCoordinations { get; set; }
        public virtual ICollection<RequestPayment> RequestPayments { get; set; }
        public virtual ICollection<ResidencyPermit> ResidencyPermits { get; set; }
        public virtual ICollection<SchoolingSearch> SchoolingSearches { get; set; }
        public virtual ICollection<SettlingIn> SettlingIns { get; set; }
        public virtual ICollection<StandaloneServiceWorkOrder> StandaloneServiceWorkOrders { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<TemporaryHousingCoordinaton> TemporaryHousingCoordinatons { get; set; }
        public virtual ICollection<TenancyManagement> TenancyManagements { get; set; }
        public virtual ICollection<Transportation> Transportations { get; set; }
        public virtual ICollection<VisaDeregistration> VisaDeregistrations { get; set; }
        public virtual ICollection<WorkPermit> WorkPermits { get; set; }
    }
}