// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.premier.Entities
{
    public partial class WorkPermit
    {
        public WorkPermit()
        {
            CommentsWorkPermits = new HashSet<CommentsWorkPermit>();
            DocumentWorkPermits = new HashSet<DocumentWorkPermit>();
            ReminderWorkPermits = new HashSet<ReminderWorkPermit>();
        }

        public int Id { get; set; }
        public DateTime AuthoDate { get; set; }
        public DateTime AuthoAcceptanceDate { get; set; }
        public int? StatusId { get; set; }
        public int? ApplicantId { get; set; }
        public string Name { get; set; }
        public int? WorkOrderServicesId { get; set; }
        public DateTime? ServiceCompletionDate { get; set; }
        public int? HostCountryId { get; set; }
        public int? HostCityId { get; set; }
        public string City { get; set; }
        public string VisaTypeId { get; set; }
        public int? ConsularServiceId { get; set; }
        public DateTime? DocumentCollectionStartDate { get; set; }
        public DateTime? DocumentCollectionCompletionDate { get; set; }
        public DateTime? DocumentDeliveryDate { get; set; }
        public DateTime? ApplicationSubmissionDate { get; set; }
        public DateTime? DocumentExpirationDate { get; set; }
        public DateTime? ApplicationApprovalDate { get; set; }
        public DateTime? AppointmentDate { get; set; }
        public string Comment { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatConsularService ConsularService { get; set; }
        public virtual CatCountry HostCountry { get; set; }
        public virtual CatStatusWorkOrder Status { get; set; }
        public virtual WorkOrderService WorkOrderServices { get; set; }
        public virtual ICollection<CommentsWorkPermit> CommentsWorkPermits { get; set; }
        public virtual ICollection<DocumentWorkPermit> DocumentWorkPermits { get; set; }
        public virtual ICollection<ReminderWorkPermit> ReminderWorkPermits { get; set; }
    }
}